import type { EngineDescriptor } from "@/shared/contracts/engine";

export const engineRegistry: EngineDescriptor[] = [
  {
    id: "company-os",
    name: "AI Company OS Foundation",
    version: "10.0",
    health: "ready",
    capabilities: ["business-core overview", "diagnostics", "worker registry", "revenue dashboard", "release manager"],
    dependencies: ["workflow", "coupang", "learning"],
  },
  {
    id: "market",
    name: "Market Intelligence Engine",
    version: "7.0",
    health: "ready",
    capabilities: ["collection", "time-series", "signals", "feature-warehouse", "ranking"],
    dependencies: ["supabase"],
  },
  {
    id: "discovery",
    name: "Product Discovery Engine",
    version: "8.0",
    health: "ready",
    capabilities: ["single-product recommendation", "bundle candidates", "human approval"],
    dependencies: ["market"],
  },
  {
    id: "supplier",
    name: "Supplier Intelligence Engine",
    version: "0.6",
    health: "ready",
    capabilities: ["supplier registry", "quote normalization", "landed-cost calculation", "3PL cost", "profit decision", "quote history", "domestic provider mapping"],
    dependencies: ["discovery"],
  },
  {
    id: "procurement",
    name: "Domestic Procurement Engine",
    version: "0.5",
    health: "ready",
    capabilities: ["Domeggook mapping", "procurement score", "purchase order", "3PL inbound plan", "commerce timeline"],
    dependencies: ["discovery", "supplier"],
  },
  {
    id: "bundle",
    name: "Bundle Intelligence Engine",
    version: "0.1",
    health: "degraded",
    capabilities: ["bundle validation"],
    dependencies: ["discovery", "supplier"],
  },
  {
    id: "workflow",
    name: "Product Workspace & Workflow Engine",
    version: "1.0",
    health: "ready",
    capabilities: ["central state machine", "automatic reconciliation", "workflow code", "task queue", "transition log", "outbox events", "product lifecycle", "commerce timeline", "cross-engine workspace"],
    dependencies: ["market", "discovery", "supplier", "procurement"],
  },
  {
    id: "listing",
    name: "Listing AI Engine",
    version: "0.5",
    health: "degraded",
    capabilities: ["title draft", "keywords", "options", "detail outline", "FAQ", "thumbnail brief", "Coupang payload draft", "human approval"],
    dependencies: ["procurement", "bundle", "coupang"],
  },
  {
    id: "coupang",
    name: "Coupang Integration Engine",
    version: "4.0",
    health: "ready",
    capabilities: ["connection test", "category metadata", "validation", "registration queue", "attempt history", "retry", "product sync", "workflow transition"],
    dependencies: ["listing"],
  },
  {
    id: "fulfillment",
    name: "3PL Fulfillment Engine",
    version: "0.1",
    health: "disabled",
    capabilities: [],
    dependencies: ["supplier", "coupang"],
  },
  {
    id: "learning",
    name: "Learning Engine",
    version: "0.1",
    health: "degraded",
    capabilities: ["feedback storage"],
    dependencies: ["market", "discovery", "coupang", "fulfillment"],
  },
];
