"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";

type Quote={id:number;product_name:string;moq:number;unit_cost:number;exchange_rate:number;lead_time_days:number;status:string;discovery_recommendation_id:number|null;bundle_recommendation_id:number|null;suppliers:{id:number;name:string;reliability_score:number}|null;sourcing_decisions:Array<{id:number;decision:string;expected_margin_rate:number;score:number}>};
type Mapping={id:number;supplier_id:number;provider:string;provider_product_id:string;provider_product_name:string;minimum_order_quantity:number;current_unit_cost:number;stock_status:string;discovery_recommendation_id:number|null;bundle_recommendation_id:number|null;suppliers:{name:string}|null};
type Order={id:number;order_number:string;product_name:string;quantity:number;total_amount:number;expected_inbound_date:string|null;status:string;procurement_score:number;suppliers:{name:string}|null;three_pl_inbound_plans:Array<{id:number;warehouse_name:string;status:string}>};
type Workflow={id:number;workflow_name:string;current_stage:string;status:string;commerce_timeline_events:Array<{id:number;title:string;stage:string;created_at:string}>};
type Dashboard={quotes:Quote[];mappings:Mapping[];orders:Order[];inbounds:unknown[];workflows:Workflow[]};
const empty:Dashboard={quotes:[],mappings:[],orders:[],inbounds:[],workflows:[]};
const won=(n:number)=>`${Math.round(Number(n)||0).toLocaleString("ko-KR")}원`;
const stageLabel:Record<string,string>={market_discovered:"시장 발견",ai_recommended:"AI 추천",human_approved:"사람 승인",supplier_mapped:"도매 상품 연결",quote_selected:"견적 선정",purchase_approved:"발주 승인",purchase_ordered:"발주 완료",three_pl_inbound:"3PL 입고",listing_ready:"상품등록 준비",coupang_registered:"쿠팡 등록",selling:"판매",learning:"학습"};
export default function ProcurementPage(){
 const[data,setData]=useState<Dashboard>(empty),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[mapping,setMapping]=useState({quoteId:"",supplierId:"",discoveryRecommendationId:"",bundleRecommendationId:"",provider:"domeggook",providerProductId:"",providerProductUrl:"",providerProductName:"",providerSku:"",minimumOrderQuantity:"1",currentUnitCost:"0",stockStatus:"unknown"});
 const[order,setOrder]=useState({quoteId:"",mappingId:"",quantity:"",notes:""});
 const[inbound,setInbound]=useState({orderId:"",warehouseName:"",warehouseCode:"",inboundReference:"",expectedInboundDate:"",expectedQuantity:"",receivingNotes:""});
 async function load(){const r=await fetch("/api/procurement/dashboard",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"조달 데이터 조회 실패");setData(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function post(path:string,body:object,ok:string){setWorking(true);setError("");setMessage("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"작업 실패");setMessage(ok);await load();return true;}catch(e){setError(e instanceof Error?e.message:"작업 오류");return false;}finally{setWorking(false);}}
 const selectedQuote=useMemo(()=>data.quotes.find(q=>String(q.id)===mapping.quoteId),[data.quotes,mapping.quoteId]);
 function onQuoteForMapping(id:string){const q=data.quotes.find(x=>String(x.id)===id);setMapping({...mapping,quoteId:id,supplierId:String(q?.suppliers?.id||""),discoveryRecommendationId:q?.discovery_recommendation_id?String(q.discovery_recommendation_id):"",bundleRecommendationId:q?.bundle_recommendation_id?String(q.bundle_recommendation_id):"",providerProductName:q?.product_name||"",minimumOrderQuantity:String(q?.moq||1),currentUnitCost:String((q?.unit_cost||0)*(q?.exchange_rate||1))});}
 async function addMapping(e:FormEvent){e.preventDefault();if(await post("/api/procurement/mappings",mapping,"국내 도매 상품 연결을 저장했습니다."))setMapping({...mapping,providerProductId:"",providerProductUrl:"",providerSku:""});}
 async function addOrder(e:FormEvent){e.preventDefault();const q=data.quotes.find(x=>String(x.id)===order.quoteId);const qty=order.quantity||String(q?.moq||1);if(await post("/api/procurement/orders",{...order,quantity:qty},"발주 승인서를 생성했습니다."))setOrder({quoteId:"",mappingId:"",quantity:"",notes:""});}
 async function addInbound(e:FormEvent){e.preventDefault();if(await post("/api/procurement/inbounds",inbound,"3PL 입고 계획을 등록했습니다."))setInbound({orderId:"",warehouseName:"",warehouseCode:"",inboundReference:"",expectedInboundDate:"",expectedQuantity:"",receivingNotes:""});}
 return <main className="dashboard">
  <section className="hero" style={{background:"linear-gradient(135deg,#14335b,#0b8a75)"}}><div><p className="eyebrow">ENGINE 3-1 · PROCUREMENT</p><h1>3-1. 발주·입고 준비</h1><p className="hero-description">승인된 AI 상품을 국내 도매 공급상품과 연결하고, 선정 견적을 발주서와 3PL 입고계획으로 전환합니다. 해외 수입 기능은 플러그인 자리만 유지하고 1차 운영에서는 비활성화합니다.</p></div><div className="hero-actions"><Link className="button-link secondary-button" href="/dashboard">7대 엔진 전체보기</Link><Link className="button-link secondary-button" href="/sourcing">3. 공급처 소싱·조달</Link><Link className="button-link secondary-button" href="/fulfillment">4. 물류·재고·출고</Link><Link className="button-link secondary-button" href="/workspace">4-1 물류 Workspace</Link><Link className="button-link secondary-button" href="/listing">5. 상품 콘텐츠 제작</Link><Link className="button-link secondary-button" href="/seller">6. 판매채널 운영</Link></div></section>
  <section className="stat-grid"><article><span>선정 견적</span><strong>{data.quotes.length}</strong></article><article><span>도매 상품 연결</span><strong>{data.mappings.length}</strong></article><article><span>발주서</span><strong>{data.orders.length}</strong></article><article><span>3PL 입고계획</span><strong>{data.orders.filter(o=>o.three_pl_inbound_plans?.length).length}</strong></article></section>
  {message&&<div className="notice success-notice">{message}</div>}{error&&<div className="notice error-notice">{error}</div>}
  <section className="sourcing-form-grid"><form className="panel" onSubmit={addMapping}><h2>도매꾹 상품 연결</h2><p className="panel-help">선정 견적과 실제 국내 도매 상품번호를 연결합니다. 현재 활성 Provider는 도매꾹과 수동 국내도매입니다.</p><div className="form-stack"><select required value={mapping.quoteId} onChange={e=>onQuoteForMapping(e.target.value)}><option value="">선정 견적 선택</option>{data.quotes.map(q=><option key={q.id} value={q.id}>{q.product_name} · {q.suppliers?.name}</option>)}</select><select value={mapping.provider} onChange={e=>setMapping({...mapping,provider:e.target.value})}><option value="domeggook">도매꾹</option><option value="manual">기타 국내도매</option><option value="domeme" disabled>도매매(후속 플러그인)</option><option value="ownerclan" disabled>오너클랜(후속 플러그인)</option></select><input required placeholder="도매 상품번호" value={mapping.providerProductId} onChange={e=>setMapping({...mapping,providerProductId:e.target.value})}/><input required placeholder="도매 상품명" value={mapping.providerProductName} onChange={e=>setMapping({...mapping,providerProductName:e.target.value})}/><input placeholder="도매 상품 URL" value={mapping.providerProductUrl} onChange={e=>setMapping({...mapping,providerProductUrl:e.target.value})}/><div className="inline-fields"><input type="number" min="1" placeholder="최소주문수량" value={mapping.minimumOrderQuantity} onChange={e=>setMapping({...mapping,minimumOrderQuantity:e.target.value})}/><input type="number" min="0" placeholder="현재 공급가" value={mapping.currentUnitCost} onChange={e=>setMapping({...mapping,currentUnitCost:e.target.value})}/></div><select value={mapping.stockStatus} onChange={e=>setMapping({...mapping,stockStatus:e.target.value})}><option value="unknown">재고 미확인</option><option value="in_stock">재고 있음</option><option value="low_stock">재고 부족</option><option value="out_of_stock">품절</option></select><button disabled={working||!selectedQuote}>도매상품 연결 저장</button></div></form>
  <form className="panel" onSubmit={addOrder}><h2>발주 승인서 생성</h2><p className="panel-help">수익성 승인된 견적만 발주할 수 있으며, 공급처 신뢰도·MOQ·리드타임·견적 신선도를 다시 검증합니다.</p><div className="form-stack"><select required value={order.quoteId} onChange={e=>{const q=data.quotes.find(x=>String(x.id)===e.target.value);setOrder({...order,quoteId:e.target.value,quantity:String(q?.moq||"")});}}><option value="">선정 견적 선택</option>{data.quotes.map(q=><option key={q.id} value={q.id}>{q.product_name} · MOQ {q.moq}</option>)}</select><select value={order.mappingId} onChange={e=>setOrder({...order,mappingId:e.target.value})}><option value="">도매 상품 연결(선택)</option>{data.mappings.map(m=><option key={m.id} value={m.id}>{m.provider_product_name} · {m.provider_product_id}</option>)}</select><input required type="number" min="1" placeholder="발주수량" value={order.quantity} onChange={e=>setOrder({...order,quantity:e.target.value})}/><textarea placeholder="발주 메모" value={order.notes} onChange={e=>setOrder({...order,notes:e.target.value})}/><button disabled={working}>발주 승인서 생성</button></div></form></section>
  <section className="panel"><div className="section-heading"><div><h2>발주 운영</h2><p>승인 → 발주완료 → 공급처확인 → 3PL입고계획 → 운송중 → 입고완료 순으로 관리합니다.</p></div><button className="table-button" onClick={()=>load().catch(e=>setError(e.message))}>새로고침</button></div><div className="quote-grid">{data.orders.length?data.orders.map(o=><article className="quote-card" key={o.id}><div className="quote-card-head"><div><span className="eyebrow">{o.order_number} · {o.suppliers?.name}</span><h3>{o.product_name}</h3></div><span className="decision decision-approve">{o.status}</span></div><div className="quote-metrics"><span>수량<strong>{o.quantity}개</strong></span><span>총 발주액<strong>{won(o.total_amount)}</strong></span><span>조달점수<strong>{Number(o.procurement_score).toFixed(0)}</strong></span><span>입고예정<strong>{o.expected_inbound_date||"미정"}</strong></span></div><div className="price-action"><select defaultValue="" onChange={e=>{if(e.target.value)post("/api/procurement/orders/status",{orderId:o.id,status:e.target.value},"발주 상태를 변경했습니다.");}}><option value="">상태 변경</option><option value="ordered">발주 완료</option><option value="supplier_confirmed">공급처 확인</option><option value="in_transit">운송 중</option><option value="received">입고 완료</option><option value="cancelled">취소</option></select></div></article>):<p className="empty-copy">아직 생성된 발주서가 없습니다.</p>}</div></section>
  <section className="sourcing-form-grid"><form className="panel" onSubmit={addInbound}><h2>3PL 입고 계획</h2><p className="panel-help">실제 3PL API 연동 전에도 창고·입고참조·수량을 표준 구조로 관리합니다.</p><div className="form-stack"><select required value={inbound.orderId} onChange={e=>{const o=data.orders.find(x=>String(x.id)===e.target.value);setInbound({...inbound,orderId:e.target.value,expectedInboundDate:o?.expected_inbound_date||"",expectedQuantity:String(o?.quantity||"")});}}><option value="">발주서 선택</option>{data.orders.filter(o=>!["received","cancelled"].includes(o.status)).map(o=><option key={o.id} value={o.id}>{o.order_number} · {o.product_name}</option>)}</select><input required placeholder="3PL 창고명" value={inbound.warehouseName} onChange={e=>setInbound({...inbound,warehouseName:e.target.value})}/><div className="inline-fields"><input placeholder="창고 코드" value={inbound.warehouseCode} onChange={e=>setInbound({...inbound,warehouseCode:e.target.value})}/><input placeholder="입고 참조번호" value={inbound.inboundReference} onChange={e=>setInbound({...inbound,inboundReference:e.target.value})}/></div><div className="inline-fields"><input type="date" value={inbound.expectedInboundDate} onChange={e=>setInbound({...inbound,expectedInboundDate:e.target.value})}/><input type="number" min="1" placeholder="입고수량" value={inbound.expectedQuantity} onChange={e=>setInbound({...inbound,expectedQuantity:e.target.value})}/></div><textarea placeholder="입고 유의사항" value={inbound.receivingNotes} onChange={e=>setInbound({...inbound,receivingNotes:e.target.value})}/><button disabled={working}>3PL 입고계획 등록</button></div></form>
  <section className="panel"><h2>Commerce Timeline</h2><p className="panel-help">상품별 시장 발견부터 발주·3PL·쿠팡 등록·판매·학습까지 누락 없이 추적하는 공통 워크플로입니다.</p><div className="workflow-list">{data.workflows.length?data.workflows.map(w=><article key={w.id} style={{border:"1px solid #dbe3f0",borderRadius:12,padding:14,marginTop:10}}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong>{w.workflow_name}</strong><span>{stageLabel[w.current_stage]||w.current_stage}</span></div><div style={{marginTop:10,color:"#5c6878",fontSize:13}}>{[...(w.commerce_timeline_events||[])].sort((a,b)=>b.id-a.id).slice(0,4).map(e=><div key={e.id}>• {e.title} · {new Date(e.created_at).toLocaleString("ko-KR")}</div>)}</div></article>):<p className="empty-copy">도매 상품을 연결하거나 발주서를 생성하면 타임라인이 시작됩니다.</p>}</div></section></section>
  <section className="panel architecture-panel"><h2>국내 도매 1차 운영 흐름</h2><div className="pipeline"><span>AI 추천 승인</span><b>→</b><span>도매꾹 연결</span><b>→</b><span>견적·수익성</span><b>→</b><span>발주 승인</span><b>→</b><span>3PL 입고계획</span><b>→</b><span>Listing AI</span><b>→</b><span>쿠팡 등록</span></div></section>
 </main>;
}
