"use client";
import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
type Order={id:number;product_name:string;status:string;total_amount:number;quantity:number;expected_inbound_date:string|null;suppliers:{name:string}|null};
type Draft={id:number;workflow_id:number;procurement_order_id:number;status:string;listing_type:string;product_name:string;coupang_title:string;search_keywords:string[];selling_points:string[];option_structure:Array<{name:string;values:string[]}>;detail_sections:Array<{heading:string;body:string}>;faq:Array<{question:string;answer:string}>;thumbnail_brief:string;compliance_checklist:string[];coupang_payload:Record<string,unknown>;revision:number;updated_at:string};
export default function ListingPage(){
 const[orders,setOrders]=useState<Order[]>([]),[drafts,setDrafts]=useState<Draft[]>([]),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const[form,setForm]=useState({orderId:"",productName:"",brandName:"공감라인",categoryName:"",targetCustomer:"",keyBenefits:"편리한 사용,실용적인 구성,합리적인 가격",optionNames:"기본 구성",listingType:"single",targetSellingPrice:"0"});
 async function load(){const r=await fetch("/api/listing/drafts",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Listing 조회 실패");setOrders(d.orders||[]);setDrafts(d.drafts||[]);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const selected=useMemo(()=>orders.find(x=>String(x.id)===form.orderId),[orders,form.orderId]);
 function choose(id:string){const o=orders.find(x=>String(x.id)===id);setForm({...form,orderId:id,productName:o?.product_name||"",listingType:"single"});}
 async function post(path:string,body:object,ok:string){setWorking(true);setError("");setMessage("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"작업 실패");setMessage(ok);await load();}catch(e){setError(e instanceof Error?e.message:"작업 오류");}finally{setWorking(false);}}
 async function generate(e:FormEvent){e.preventDefault();await post("/api/listing/generate",form,"쿠팡 Listing 초안을 생성했습니다.");}
 return <main className="dashboard">
  <section className="hero" style={{background:"linear-gradient(135deg,#4b1b78,#b34f12)"}}><div><p className="eyebrow">LISTING AI ENGINE · v9.5</p><h1>쿠팡 상품등록 초안 제작센터</h1><p className="hero-description">조달 승인 상품을 상품명·키워드·옵션·상세페이지·FAQ·썸네일 지시서와 쿠팡 등록 JSON 초안으로 변환합니다. 자동 생성 후 사람 승인 단계를 유지합니다.</p></div><div className="hero-actions"><Link className="button-link secondary-button" href="/workspace">상품 Workspace</Link><Link className="button-link secondary-button" href="/procurement">조달·발주</Link><Link className="button-link secondary-button" href="/seller">쿠팡 등록 Queue</Link><Link className="button-link secondary-button" href="/coupang/register">수동 등록</Link></div></section>
  <section className="stat-grid"><article><span>조달 상품</span><strong>{orders.length}</strong></article><article><span>Listing 초안</span><strong>{drafts.length}</strong></article><article><span>승인 초안</span><strong>{drafts.filter(x=>x.status==="approved").length}</strong></article><article><span>등록 완료</span><strong>{drafts.filter(x=>x.status==="registered").length}</strong></article></section>
  {message&&<div className="notice success-notice">{message}</div>}{error&&<div className="notice error-notice">{error}</div>}
  <section className="sourcing-form-grid"><form className="panel" onSubmit={generate}><h2>Listing 초안 생성</h2><p className="panel-help">실제 상품정보와 인증·고시정보는 최종 등록 전에 반드시 검토하세요.</p><div className="form-stack"><select required value={form.orderId} onChange={e=>choose(e.target.value)}><option value="">발주 상품 선택</option>{orders.map(o=><option key={o.id} value={o.id}>{o.product_name} · {o.status}</option>)}</select><input required placeholder="상품명" value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})}/><div className="inline-fields"><input placeholder="브랜드" value={form.brandName} onChange={e=>setForm({...form,brandName:e.target.value})}/><input placeholder="카테고리" value={form.categoryName} onChange={e=>setForm({...form,categoryName:e.target.value})}/></div><input placeholder="목표 고객" value={form.targetCustomer} onChange={e=>setForm({...form,targetCustomer:e.target.value})}/><textarea placeholder="핵심 장점, 쉼표 구분" value={form.keyBenefits} onChange={e=>setForm({...form,keyBenefits:e.target.value})}/><input placeholder="옵션 값, 쉼표 구분" value={form.optionNames} onChange={e=>setForm({...form,optionNames:e.target.value})}/><div className="inline-fields"><select value={form.listingType} onChange={e=>setForm({...form,listingType:e.target.value})}><option value="single">단일상품</option><option value="set">세트상품</option><option value="bundle">묶음상품</option><option value="multipack">다중수량</option></select><input type="number" min="0" placeholder="목표 판매가" value={form.targetSellingPrice} onChange={e=>setForm({...form,targetSellingPrice:e.target.value})}/></div><button disabled={working||!selected}>Listing 초안 생성</button></div></form>
  <section className="panel"><h2>생성 원칙</h2><div className="principle-grid"><span>사실 기반 문구</span><span>과장 표현 금지</span><span>고시정보 확인</span><span>인증 대상 검토</span><span>옵션·구성 일치</span><span>사람 최종 승인</span></div><p className="panel-help" style={{marginTop:14}}>현재 버전은 내부 규칙 엔진으로 안정적인 초안을 만듭니다. 추후 LLM Provider를 연결해 문구 다양화와 이미지 프롬프트 품질을 높일 수 있습니다.</p></section></section>
  <section className="panel"><div className="section-heading"><div><h2>Listing Drafts</h2><p>초안 승인 후 기존 쿠팡 등록 화면으로 전달합니다.</p></div><button className="secondary-button" onClick={()=>load().catch(e=>setError(e.message))}>새로고침</button></div><div style={{display:"grid",gap:14}}>{drafts.length?drafts.map(d=><article key={d.id} style={{border:"1px solid #d9e1ec",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"start"}}><div><small>revision {d.revision} · {d.listing_type} · {d.status}</small><h3 style={{margin:"6px 0"}}>{d.coupang_title}</h3><p>{d.search_keywords?.join(" · ")}</p></div><div className="card-actions"><button disabled={working} onClick={()=>post("/api/listing/status",{id:d.id,status:"approved"},"Listing 초안을 승인했습니다.")}>승인</button><button className="secondary-button" disabled={working} onClick={()=>post("/api/listing/status",{id:d.id,status:"reviewing"},"검토 상태로 변경했습니다.")}>검토</button>{d.status==="approved"&&<Link className="button-link" href={`/seller`}>등록 Queue</Link>}</div></div><div className="score-pills">{(d.selling_points||[]).map((x,i)=><span key={i}>{x}</span>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10,marginTop:12}}><div><strong>옵션</strong><p>{(d.option_structure||[]).map(x=>`${x.name}: ${x.values.join(", ")}`).join(" / ")}</p></div><div><strong>썸네일 지시서</strong><p>{d.thumbnail_brief}</p></div><div><strong>필수 점검</strong><p>{(d.compliance_checklist||[]).join(" · ")}</p></div></div><details><summary>상세페이지·FAQ·쿠팡 JSON 보기</summary><pre style={{whiteSpace:"pre-wrap",fontSize:12,background:"#f6f8fb",padding:12,borderRadius:10}}>{JSON.stringify({detailSections:d.detail_sections,faq:d.faq,coupangPayload:d.coupang_payload},null,2)}</pre></details></article>):<p className="empty-copy">조달 상품을 선택해 Listing 초안을 생성하세요.</p>}</div></section>
  <section className="panel architecture-panel"><h2>등록 준비 흐름</h2><div className="pipeline"><span>조달 승인</span><b>→</b><span>Listing 초안</span><b>→</b><span>인증·고시 검토</span><b>→</b><span>사람 승인</span><b>→</b><span>쿠팡 Validation</span><b>→</b><span>등록</span></div></section>
 </main>;
}
