import type { ListingContentPacket, ListingPipelineIssue } from "@/shared/domain/listing-content";

function Gate({ label, value }: { label: string; value: "PASS" | "FAIL" }) {
  return <span className={value === "PASS" ? "status-badge status-approved" : "status-badge status-rejected"}>{label}: {value}</span>;
}

function Issues({ severity, issues }: { severity: ListingPipelineIssue["severity"]; issues: readonly ListingPipelineIssue[] }) {
  const selected = issues.filter((entry) => entry.severity === severity);
  return <article className="attribute-card"><strong>{severity} ({selected.length})</strong>{selected.length === 0 ? <p>없음</p> : <ul>{selected.map((entry) => <li key={`${entry.code}:${entry.path}`}><code>{entry.path}</code> · {entry.code} · {entry.message}</li>)}</ul>}</article>;
}

export function ListingContentReview({ packet }: { packet: ListingContentPacket }) {
  const blockers = packet.issues.filter(({ severity }) => severity === "BLOCKER").length;
  return <div className="dashboard">
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">EVIDENCE-BASED CONTENT PACKET</p><h2>{packet.title.value || "제목 생성 차단"}</h2></div><span className={blockers === 0 ? "status-badge status-approved" : "status-badge status-rejected"}>{packet.status}</span></div><p className="panel-help">상품 {packet.subjectId} · packet {packet.packetId}</p><p><strong>공급처 trust:</strong> {packet.supplierTrust.sourceId} · {packet.supplierTrust.version} · {packet.supplierTrust.status}</p><p><strong>capability digest:</strong> {packet.supplierTrust.capabilityDigest}</p><p><strong>콘텐츠 승인:</strong> {packet.approval.contentApproved ? "승인" : "미승인"} · <strong>실제 게시 권한:</strong> {packet.approval.livePublishAuthorized ? "승인" : "별도 승인 필요"}</p></section>
    <section className="stat-grid"><article><span>최소 등록적합성</span><strong>{blockers === 0 ? "PASS" : `BLOCKED ${blockers}`}</strong></article><article><span>전환 준비도</span><strong>{packet.conversion.readiness}</strong></article><article><span>전환 confidence</span><strong>{packet.conversion.confidence}</strong></article><article><span>선택 variant</span><strong>{packet.selectedVariantId || "NONE"}</strong></article></section>
    <section className="panel"><h2>BLOCKER / WARNING / OPTIMIZATION_PENDING</h2><div className="attribute-list"><Issues severity="BLOCKER" issues={packet.issues} /><Issues severity="WARNING" issues={packet.issues} /><Issues severity="OPTIMIZATION_PENDING" issues={packet.issues} /></div></section>
    <section className="panel"><h2>제목 토큰과 검색키워드 근거</h2><div className="attribute-list">{packet.title.tokens.map((token) => <article className="attribute-card" key={`${token.field}:${token.text}`}><strong>{token.rank}. {token.text}</strong><p>{token.rationale} · confidence {token.confidence}</p><p>facts: {token.provenance.factIds.join(", ")}</p></article>)}</div><div className="value-chips">{packet.keywords.map((keyword) => <span key={`${keyword.field}:${keyword.text}`}>{keyword.text} · {keyword.field}</span>)}</div></section>
    <section className="panel"><h2>대표·추가·상세 자산 manifest</h2><div className="attribute-list">{packet.assets.map((asset) => <article className="attribute-card" key={asset.outputAssetId}><strong>{asset.role} · {asset.shotType} · {asset.outputAssetId}</strong><p>{asset.disposition} · {asset.width}×{asset.height} · {asset.mimeType} · {asset.transformation}</p><p>output: {asset.outputReference} · digest: {asset.outputDigest}</p><p>사용권 {asset.useRights} · 편집권 {asset.editRights} · transform {asset.transformationReference} · output rights {asset.outputRightsReference}</p><div className="value-chips">{Object.entries(asset.review).map(([name, result]) => <Gate key={name} label={name} value={result} />)}</div></article>)}</div></section>
    <section className="panel"><h2>모바일 상세페이지 render</h2><div className="value-chips">{Object.entries(packet.detailPage.review).map(([name, result]) => <Gate key={name} label={name} value={result} />)}</div><iframe title="모바일 상세페이지 검토 render" srcDoc={packet.detailPage.html} style={{ width: "100%", maxWidth: 780, minHeight: 360, border: "1px solid #d8dee9", marginTop: 16 }} sandbox="" /></section>
    <section className="panel"><h2>후보 비교와 사람 선택</h2>{packet.conversion.candidates.map((candidate) => <article className="attribute-card" key={candidate.variantId}><strong>{candidate.variantId === packet.conversion.selectedVariantId ? "선택됨 · " : "후보 · "}{candidate.variantId}</strong><p>{candidate.title}</p><p>{candidate.keywords.join(", ")}</p><p>creative: {candidate.creativePlan.join(" → ")} · detail: {candidate.detailPlan.join(" → ")}</p><p>{candidate.rationale.join(" · ")} · confidence {candidate.confidence}</p></article>)}</section>
    <section className="panel"><h2>정책 snapshot과 전환 근거</h2>{packet.conversion.sourceSnapshots.map((source) => <article className="attribute-card" key={source.sourceId}><strong>P{source.priority} · {source.kind} · {source.sourceId}</strong><p>{source.appliesTo}</p><p>관찰 {source.observedAt} · version {source.version} · digest {source.digest}</p><p>한계: {source.limitation}</p></article>)}{packet.conversion.marketObservations.map((observation) => <article className="attribute-card" key={observation.observationId}><strong>P2 · CATEGORY_MARKET_OBSERVATION · {observation.observationId}</strong><p>{observation.attributeFields.join(", ")} · shots {observation.publicSignals.imageShotTypes.join(", ")}</p><p>{observation.sourceReferences.join(", ")} · {observation.observedAt} · digest {observation.digest}</p><p>한계: {observation.limitation} · 원문/이미지 복제 {String(observation.copiedTextOrImage)}</p></article>)}</section>
    <section className="panel"><h2>학습·rollback·provider 경계</h2><p>{packet.conversion.optimizationRationale.join(" · ")}</p><p>승인된 순차 revision만 사용 · 병렬 중복 listing 금지 · traffic/profit/return guardrail 필수</p><p>Generation: {packet.generation.mode} · external text provider {String(packet.generation.externalTextProviderUsed)} · generative asset {packet.generation.generatedAssetCount}</p><p>Rollback: {packet.conversion.learningPlan.rollbackPlan}</p>{packet.assumptions.length > 0 && <div><strong>Owner-approved assumptions</strong><ul>{packet.assumptions.map((assumption) => <li key={assumption.targetField}>{assumption.targetField}: {assumption.assumption} · {assumption.approvalReference}</li>)}</ul></div>}</section>
  </div>;
}
