import type { ListingContentPacket } from "@/shared/domain/listing-content";

function Gate({ label, value }: { label: string; value: "PASS" | "FAIL" }) {
  return <span className={value === "PASS" ? "status-badge status-approved" : "status-badge status-rejected"}>{label}: {value}</span>;
}

export function ListingContentReview({ packet }: { packet: ListingContentPacket }) {
  return <div className="dashboard">
    <section className="panel"><div className="panel-heading"><div><p className="eyebrow">EVIDENCE-BASED CONTENT PACKET</p><h2>{packet.title.value || "제목 생성 차단"}</h2></div><span className={packet.status === "REGISTRATION_READY" ? "status-badge status-approved" : "status-badge status-rejected"}>{packet.status}</span></div><p className="panel-help">상품 {packet.subjectId} · packet {packet.packetId}</p><p><strong>콘텐츠 승인:</strong> {packet.approval.contentApproved ? "승인" : "미승인"} · <strong>실제 게시 권한:</strong> {packet.approval.livePublishAuthorized ? "승인" : "별도 승인 필요"}</p></section>
    <section className="panel"><h2>제목 토큰과 검색키워드 근거</h2><div className="attribute-list">{packet.title.tokens.map((token) => <article className="attribute-card" key={`${token.text}:${token.provenance.factIds.join()}`}><strong>{token.text}</strong><p>facts: {token.provenance.factIds.join(", ")}</p></article>)}</div><div className="value-chips">{packet.keywords.map((keyword) => <span key={`${keyword.text}:${keyword.provenance.factIds.join()}`}>{keyword.text}</span>)}</div></section>
    <section className="panel"><h2>대표·추가·상세 자산 manifest</h2><div className="attribute-list">{packet.assets.map((asset) => <article className="attribute-card" key={asset.outputAssetId}><strong>{asset.role} · {asset.outputAssetId}</strong><p>{asset.width}×{asset.height} · {asset.mimeType} · {asset.transformation}</p><p>digest: {asset.outputDigest}</p><p>사용권 {asset.useRights} · 편집권 {asset.editRights}</p><div className="value-chips">{Object.entries(asset.review).map(([name, result]) => <Gate key={name} label={name} value={result} />)}</div></article>)}</div></section>
    <section className="panel"><h2>모바일 상세페이지 render</h2><div className="value-chips">{Object.entries(packet.detailPage.review).map(([name, result]) => <Gate key={name} label={name} value={result} />)}</div><iframe title="모바일 상세페이지 검토 render" srcDoc={packet.detailPage.html} style={{ width: "100%", maxWidth: 780, minHeight: 360, border: "1px solid #d8dee9", marginTop: 16 }} sandbox="" /></section>
    <section className="panel"><h2>등록 적합성 / 전환 준비도</h2><p><strong>Registration:</strong> {packet.status} · <strong>Conversion:</strong> {packet.conversion.readiness} ({packet.conversion.confidence})</p><p>목표: qualified purchase conversion + 실제 귀속이익, 취소·반품·환불·오인·정책위반 최소화</p></section>
    <section className="panel"><h2>후보와 선택 근거</h2>{packet.conversion.candidates.map((candidate) => <article className="attribute-card" key={candidate.variantId}><strong>{candidate.variantId === packet.conversion.selectedVariantId ? "선택됨 · " : "후보 · "}{candidate.variantId}</strong><p>{candidate.title}</p><p>{candidate.keywords.join(", ")}</p><p>{candidate.rationale.join(" · ")}</p></article>)}<p>정책/카테고리 snapshot: {packet.conversion.sourceSnapshotIds.join(", ")}</p><p>학습: 승인된 순차 revision만 사용 · 병렬 중복 listing 금지 · profit/return guardrail 필수</p></section>
    <section className="panel"><h2>BLOCKER / WARNING / OPTIMIZATION_PENDING</h2>{packet.issues.length === 0 ? <p className="notice success-notice">모든 offline gate가 통과했습니다. 실제 게시 권한은 여전히 별도입니다.</p> : <ul>{packet.issues.map((entry) => <li key={`${entry.code}:${entry.path}`}><strong>{entry.severity}</strong> · {entry.path} · {entry.code} · {entry.message}</li>)}</ul>}</section>
  </div>;
}
