-- 공감라인 AI Commerce OS v4.0 - 핵심 스키마
-- 안전성 원칙
-- 1) 기존 테이블/데이터를 삭제하지 않습니다.
-- 2) CREATE TABLE IF NOT EXISTS와 조건부 제약조건만 사용합니다.
-- 3) v3.2 환경에 products 테이블이 없어도 실행되도록 product_id에는 외래키를 강제하지 않습니다.
-- 4) RLS 정책은 별도 003 파일에서 적용합니다.

begin;

create table if not exists public.fulfillment_providers (
  id bigint generated by default as identity primary key,
  name text not null,
  provider_code text not null unique,
  website_url text,
  contact text,
  supports_kitting boolean not null default false,
  supports_coupang_growth boolean not null default false,
  supports_api boolean not null default false,
  domeggook_partner boolean not null default false,
  receiving_fee numeric(14,2) not null default 0 check (receiving_fee >= 0),
  storage_fee_per_unit numeric(14,2) not null default 0 check (storage_fee_per_unit >= 0),
  picking_fee numeric(14,2) not null default 0 check (picking_fee >= 0),
  kitting_fee numeric(14,2) not null default 0 check (kitting_fee >= 0),
  packaging_fee numeric(14,2) not null default 0 check (packaging_fee >= 0),
  outbound_fee numeric(14,2) not null default 0 check (outbound_fee >= 0),
  coupang_inbound_fee numeric(14,2) not null default 0 check (coupang_inbound_fee >= 0),
  return_handling_fee numeric(14,2) not null default 0 check (return_handling_fee >= 0),
  lead_time_days integer not null default 1 check (lead_time_days >= 0),
  api_config jsonb,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_projects (
  id bigint generated by default as identity primary key,
  name text not null,
  product_type text not null check (product_type in ('SINGLE','MULTIPACK','BUNDLE')),
  status text not null default 'DRAFT' check (status in ('DRAFT','ANALYZING','APPROVED','INBOUND_READY','INBOUND','SELLING','PAUSED')),
  target_keyword text,
  sale_price numeric(14,2) not null default 0 check (sale_price >= 0),
  monthly_sales_units integer not null default 0 check (monthly_sales_units >= 0),
  marketplace_fee_rate numeric(7,6) not null default 0.11 check (marketplace_fee_rate between 0 and 1),
  advertising_rate numeric(7,6) not null default 0.08 check (advertising_rate between 0 and 1),
  safety_stock_rate numeric(7,6) not null default 0.20 check (safety_stock_rate between 0 and 5),
  selected_provider_id bigint,
  business_score numeric(6,2),
  competition_score numeric(6,2),
  profitability_score numeric(6,2),
  fulfillment_score numeric(6,2),
  supply_risk_score numeric(6,2),
  grade text,
  analysis_result jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_project_components (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.commerce_projects(id) on delete cascade,
  product_id bigint,
  product_no text,
  title text not null,
  quantity integer not null default 1 check (quantity > 0),
  unit_supply_price numeric(14,2) not null default 0 check (unit_supply_price >= 0),
  inbound_shipping_cost numeric(14,2) not null default 0 check (inbound_shipping_cost >= 0),
  supplier_id text,
  supplier_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.competition_analyses (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.commerce_projects(id) on delete cascade,
  demand_score numeric(6,2) not null default 50 check (demand_score between 0 and 100),
  competition_score numeric(6,2) not null default 50 check (competition_score between 0 and 100),
  differentiation_score numeric(6,2) not null default 50 check (differentiation_score between 0 and 100),
  review_barrier_score numeric(6,2) not null default 50 check (review_barrier_score between 0 and 100),
  price_competitiveness_score numeric(6,2) not null default 50 check (price_competitiveness_score between 0 and 100),
  data_confidence numeric(6,2) not null default 30 check (data_confidence between 0 and 100),
  source_type text not null default 'MANUAL',
  source_collected_at timestamptz,
  raw_data jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.inbound_orders (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.commerce_projects(id) on delete cascade,
  provider_id bigint references public.fulfillment_providers(id) on delete set null,
  status text not null default 'DRAFT' check (status in ('DRAFT','ORDERED','SUPPLIER_SHIPPED','3PL_RECEIVED','INSPECTING','KITTING','READY_FOR_COUPANG','COUPANG_SHIPPED','COUPANG_RECEIVED','CANCELLED')),
  planned_quantity integer not null default 0 check (planned_quantity >= 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  defective_quantity integer not null default 0 check (defective_quantity >= 0),
  tracking_number text,
  coupang_inbound_reference text,
  expected_at timestamptz,
  received_at timestamptz,
  shipped_to_coupang_at timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_balances (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.commerce_projects(id) on delete cascade,
  product_id bigint,
  provider_id bigint references public.fulfillment_providers(id) on delete set null,
  available_quantity integer not null default 0 check (available_quantity >= 0),
  reserved_quantity integer not null default 0 check (reserved_quantity >= 0),
  inbound_quantity integer not null default 0 check (inbound_quantity >= 0),
  safety_stock_quantity integer not null default 0 check (safety_stock_quantity >= 0),
  updated_at timestamptz not null default now(),
  unique(project_id, product_id, provider_id)
);

-- commerce_projects -> fulfillment_providers FK를 재실행 가능하게 조건부 추가
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'commerce_projects_provider_fk'
      AND conrelid = 'public.commerce_projects'::regclass
  ) THEN
    ALTER TABLE public.commerce_projects
      ADD CONSTRAINT commerce_projects_provider_fk
      FOREIGN KEY (selected_provider_id)
      REFERENCES public.fulfillment_providers(id)
      ON DELETE SET NULL;
  END IF;
END $$;

create index if not exists commerce_projects_status_idx on public.commerce_projects(status);
create index if not exists commerce_projects_provider_idx on public.commerce_projects(selected_provider_id);
create index if not exists commerce_project_components_project_idx on public.commerce_project_components(project_id);
create index if not exists competition_analyses_project_idx on public.competition_analyses(project_id);
create index if not exists inbound_orders_project_idx on public.inbound_orders(project_id);
create index if not exists inbound_orders_provider_idx on public.inbound_orders(provider_id);
create index if not exists inventory_balances_project_idx on public.inventory_balances(project_id);

-- updated_at 자동 갱신 함수
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_fulfillment_providers_updated_at') THEN
    CREATE TRIGGER trg_fulfillment_providers_updated_at
    BEFORE UPDATE ON public.fulfillment_providers
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_commerce_projects_updated_at') THEN
    CREATE TRIGGER trg_commerce_projects_updated_at
    BEFORE UPDATE ON public.commerce_projects
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_inbound_orders_updated_at') THEN
    CREATE TRIGGER trg_inbound_orders_updated_at
    BEFORE UPDATE ON public.inbound_orders
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_inventory_balances_updated_at') THEN
    CREATE TRIGGER trg_inventory_balances_updated_at
    BEFORE UPDATE ON public.inventory_balances
    FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
  END IF;
END $$;

commit;
