create table if not exists public.products (
  id bigint generated by default as identity primary key,

  product_no text not null unique,
  keyword text,

  title text not null,
  thumbnail text,
  product_url text,

  supply_price integer not null default 0,
  minimum_order_quantity integer not null default 1,
  initial_purchase_amount integer not null default 0,

  estimated_sale_price integer not null default 0,
  marketplace_fee integer not null default 0,
  advertising_cost integer not null default 0,
  logistics_cost integer not null default 0,
  return_reserve integer not null default 0,

  estimated_profit integer not null default 0,
  margin_rate numeric(6, 2) not null default 0,
  break_even_sale_price integer not null default 0,

  basic_score integer not null default 0,
  recommendation text,

  seller_id text,
  seller_name text,

  available_on_domeggook boolean not null default false,
  supply_available boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Allow public read products"
on public.products
for select
to anon
using (true);

create policy "Allow public insert products"
on public.products
for insert
to anon
with check (true);

create policy "Allow public update products"
on public.products
for update
to anon
using (true)
with check (true);
