"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";

type Draft={id:number;workflow_id:number;product_name:string;coupang_title:string;status:string;updated_at:string};
type Job={id:number;job_code:string;workflow_id:number;listing_draft_id:number;status:string;mode:string;validation_issues:Array<{path?:string;message?:string}>;seller_product_id:string|null;coupang_status:string|null;last_error:string|null;attempt_count:number;updated_at:string;listing_drafts?:{coupang_title?:string;product_name?:string;status?:string};commerce_workflows?:{workflow_code?:string;workflow_name?:string;current_stage?:string}};
type Attempt={id:number;job_id:number;attempt_no:number;action:string;success:boolean;response_status:number|null;error_message:string|null;created_at:string};

export default function CoupangSellerPage(){
 const[drafts,setDrafts]=useState<Draft[]>([]),[jobs,setJobs]=useState<Job[]>([]),[attempts,setAttempts]=useState<Attempt[]>([]),[selected,setSelected]=useState(""),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/coupang/seller/jobs",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"등록센터 조회 실패");setDrafts(d.drafts||[]);setJobs(d.jobs||[]);setAttempts(d.attempts||[]);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const stats=useMemo(()=>({ready:jobs.filter(x=>x.status==="ready").length,failed:jobs.filter(x=>["validation_failed","failed"].includes(x.status)).length,submitted:jobs.filter(x=>["submitted","registered"].includes(x.status)).length}),[jobs]);
 async function act(path:string,body:object,ok:string){setWorking(true);setError("");setMessage("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"작업 실패");setMessage(ok);await load();}catch(e){setError(e instanceof Error?e.message:"작업 오류");}finally{setWorking(false);}}
 return <main className="dashboard">
  <section className="hero" style={{background:"linear-gradient(135deg,#16335b,#0f8b8d)"}}><div><p className="eyebrow">ENGINE 6 · SALES CHANNELS</p><h1>6. 판매채널 운영</h1><p className="hero-description">승인 Listing을 등록 Queue로 전환하고 Validation·실등록·실패·재시도·등록결과를 Workflow와 함께 관리합니다.</p></div><div className="hero-actions"><button disabled={working} onClick={()=>act("/api/coupang/seller/sync",{},"쿠팡 상품 목록을 동기화했습니다.")}>상품 동기화</button></div></section>
  <section className="stat-grid"><article><span>등록 작업</span><strong>{jobs.length}</strong></article><article><span>등록 준비</span><strong>{stats.ready}</strong></article><article><span>오류·검토</span><strong>{stats.failed}</strong></article><article><span>제출·등록</span><strong>{stats.submitted}</strong></article></section>
  {message&&<div className="notice success-notice">{message}</div>}{error&&<div className="notice error-notice">{error}</div>}
  <section className="panel"><div className="section-heading"><div><h2>승인 Listing → 등록 Queue</h2><p>승인된 초안을 선택하면 기본 Validation을 즉시 실행하고 등록 작업을 생성합니다.</p></div><button className="secondary-button" onClick={()=>load().catch(e=>setError(e.message))}>새로고침</button></div><div className="inline-fields"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">승인 Listing 선택</option>{drafts.map(d=><option key={d.id} value={d.id}>{d.coupang_title} · {d.status}</option>)}</select><button disabled={working||!selected} onClick={()=>act("/api/coupang/seller/jobs",{listingDraftId:Number(selected)},"쿠팡 등록 작업을 생성했습니다.")}>등록 작업 생성</button></div></section>
  <section className="panel"><h2>Registration Queue</h2><div style={{display:"grid",gap:14}}>{jobs.length?jobs.map(job=><article key={job.id} style={{border:"1px solid #d9e1ec",borderRadius:14,padding:16}}><div style={{display:"flex",justifyContent:"space-between",gap:14,alignItems:"start",flexWrap:"wrap"}}><div><small>{job.job_code} · {job.commerce_workflows?.workflow_code||`WF #${job.workflow_id}`}</small><h3 style={{margin:"6px 0"}}>{job.listing_drafts?.coupang_title||job.commerce_workflows?.workflow_name||"상품명 없음"}</h3><p>상태 <strong>{job.status}</strong> · 시도 {job.attempt_count}회 · 쿠팡 ID {job.seller_product_id||"-"}</p>{job.last_error&&<p style={{color:"#b42318"}}>{job.last_error}</p>}</div><div className="card-actions"><button disabled={working} onClick={()=>act(`/api/coupang/seller/jobs/${job.id}`,{action:"validate"},"Validation을 다시 실행했습니다.")}>검증</button><Link className="button-link" href={`/coupang/register?listingDraftId=${job.listing_draft_id}&workflowId=${job.workflow_id}&jobId=${job.id}`}>등록 화면</Link><button className="secondary-button" disabled={working} onClick={()=>act(`/api/coupang/seller/jobs/${job.id}`,{action:"retry"},"재시도 준비 상태로 변경했습니다.")}>재시도</button></div></div>{job.validation_issues?.length>0&&<details open><summary>Validation 문제 {job.validation_issues.length}건</summary><ul>{job.validation_issues.map((x,i)=><li key={i}><strong>{x.path||"payload"}</strong> — {x.message||"확인 필요"}</li>)}</ul></details>}</article>):<p className="empty-copy">승인 Listing에서 등록 작업을 생성하세요.</p>}</div></section>
  <section className="panel"><h2>최근 등록 시도</h2><div style={{display:"grid",gap:8}}>{attempts.slice(0,20).map(a=><div key={a.id} style={{display:"grid",gridTemplateColumns:"90px 100px 1fr 170px",gap:10,borderBottom:"1px solid #edf0f4",padding:"9px 0"}}><strong>Job #{a.job_id}</strong><span>{a.action}</span><span>{a.success?"성공":a.error_message||`HTTP ${a.response_status||"-"}`}</span><small>{new Date(a.created_at).toLocaleString("ko-KR")}</small></div>)}</div></section>
  <section className="panel architecture-panel"><h2>등록 운영 흐름</h2><div className="pipeline"><span>Listing 승인</span><b>→</b><span>Queue 생성</span><b>→</b><span>Validation</span><b>→</b><span>사람 확인</span><b>→</b><span>쿠팡 제출</span><b>→</b><span>결과 추적</span><b>→</b><span>판매 모니터링</span></div></section>
 </main>;
}
