"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Decision="approve"|"review"|"hold"|"reject";
type Single={id:number,status:string,decision_action:Decision,decision_score:number,ai_score:number,market_score:number,growth_score:number,competition_score:number,supply_score:number,season_score:number,risk_score:number,profit_score:number,confidence:number,estimated_units_low:number,estimated_units_high:number,recommendation_reason:string,risk_explanation:string,market_products:{title:string,category:string|null,brand:string|null,thumbnail_url:string|null}|null};
type BundleItem={role:string,quantity:number,market_products:{title:string,thumbnail_url:string|null}|null};
type Bundle={id:number,bundle_name:string,status:string,decision_action:Decision,decision_score:number,ai_score:number,synergy_score:number,convenience_score:number,differentiation_score:number,margin_score:number,risk_score:number,confidence:number,recommendation_reason:string,ai_bundle_items:BundleItem[]};
type Run={id:number,status:string,processed_count:number,recommendation_count:number,bundle_count:number,decision_summary:Record<string,number>,started_at:string,completed_at:string|null,error_message:string|null};
const labels:Record<Decision,string>={approve:"자동 승인 추천",review:"검토 추천",hold:"보류",reject:"제외"};
export default function DiscoveryPage(){const[singles,setSingles]=useState<Single[]>([]),[bundles,setBundles]=useState<Bundle[]>([]),[runs,setRuns]=useState<Run[]>([]),[working,setWorking]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState(""),[filter,setFilter]=useState<"all"|Decision>("all");
async function load(){const[r1,r2,r3]=await Promise.all([fetch("/api/discovery/recommendations",{cache:"no-store"}),fetch("/api/discovery/bundles",{cache:"no-store"}),fetch("/api/discovery/runs",{cache:"no-store"})]);const[d1,d2,d3]=await Promise.all([r1.json(),r2.json(),r3.json()]);if(d1.success)setSingles(d1.recommendations??[]);if(d2.success)setBundles(d2.bundles??[]);if(d3.success)setRuns(d3.runs??[]);}
useEffect(()=>{void load();},[]);
async function act(path:string,body:object,ok:string){setWorking(true);setError("");setMessage("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"작업 실패");const detail=d.result?` 처리 ${d.result.processedCount}개 · 추천 ${d.result.singleCount}개 · 묶음 ${d.result.bundleCount}개`:"";setMessage(ok+detail);await load();}catch(e){setError(e instanceof Error?e.message:"작업 오류");}finally{setWorking(false);}}
const shown=useMemo(()=>filter==="all"?singles:singles.filter(x=>x.decision_action===filter),[singles,filter]);const count=(d:Decision)=>singles.filter(x=>x.decision_action===d).length;const latest=runs[0];
return <main className="dashboard"><section className="hero discovery-hero"><div><p className="eyebrow">ENGINE 1-1 · DISCOVERY</p><h1>1-1. 시장 후보 발굴·의사결정</h1><p className="hero-description">시장 Feature를 점수화하고 추천·검토·보류·제외를 자동 판정합니다. 모든 결정은 근거, 위험, 신뢰도와 함께 기록됩니다.</p></div><div className="hero-actions"><Link className="button-link secondary-button" href="/dashboard">7대 엔진 전체보기</Link><Link className="button-link secondary-button" href="/market">1. 시장정보·아이템 발굴</Link><Link className="button-link secondary-button" href="/sourcing">3. 공급처 소싱·조달</Link><button disabled={working} onClick={()=>act("/api/discovery/generate",{limit:100},"AI 의사결정을 완료했습니다.")}>{working?"분석 중...":"AI 의사결정 실행"}</button></div></section>
<section className="stat-grid decision-stats"><article><span>분석 추천</span><strong>{singles.length}</strong></article><article><span>승인 추천</span><strong>{count("approve")}</strong></article><article><span>검토 필요</span><strong>{count("review")}</strong></article><article><span>보류·제외</span><strong>{count("hold")+count("reject")}</strong></article></section>{message&&<div className="notice success-notice">{message}</div>}{error&&<div className="notice error-notice">{error}</div>}
<section className="panel decision-run-panel"><div><h2>최근 Decision Run</h2><p>{latest?`${new Date(latest.started_at).toLocaleString()} · ${latest.status} · 입력 ${latest.processed_count||0}개 · 묶음 ${latest.bundle_count||0}개`:"아직 실행 이력이 없습니다."}</p></div>{latest?.error_message&&<span className="danger-text">{latest.error_message}</span>}</section>
<section className="panel"><div className="section-heading"><div><h2>AI 단일상품 의사결정</h2><p>시장·성장·경쟁·공급·계절·마진·위험 점수를 분리해 설명합니다.</p></div><div className="decision-filters">{(["all","approve","review","hold","reject"] as const).map(x=><button key={x} className={filter===x?"active secondary-button":"secondary-button"} onClick={()=>setFilter(x)}>{x==="all"?"전체":labels[x]}</button>)}</div></div><div className="discovery-grid">{shown.length?shown.map(x=><article className={`discovery-card decision-${x.decision_action}`} key={x.id}>{x.market_products?.thumbnail_url&&<img src={x.market_products.thumbnail_url} alt=""/>}<div><div className="decision-card-head"><span className={`decision-badge ${x.decision_action}`}>{labels[x.decision_action]}</span><span className={`grade grade-${x.decision_score>=82?"S":x.decision_score>=68?"A":"B"}`}>{Math.round(x.decision_score)}</span></div><h3>{x.market_products?.title}</h3><p>{x.market_products?.category||x.market_products?.brand||"시장상품"}</p><div className="score-pills"><span>시장 {Math.round(x.market_score)}</span><span>성장 {Math.round(x.growth_score)}</span><span>경쟁 {Math.round(x.competition_score)}</span><span>공급 {Math.round(x.supply_score)}</span><span>계절 {Math.round(x.season_score)}</span><span>마진 {Math.round(x.profit_score)}</span><span>위험 {Math.round(x.risk_score)}</span></div><strong>월 예상 {x.estimated_units_low.toLocaleString()}~{x.estimated_units_high.toLocaleString()}개 · 신뢰도 {x.confidence}%</strong><div className="explain-box"><b>추천 근거</b><p>{x.recommendation_reason}</p><b>위험 검토</b><p>{x.risk_explanation}</p></div><div className="card-actions"><button disabled={working} onClick={()=>act("/api/discovery/approve",{kind:"single",id:x.id,status:"approved"},"단일상품 후보를 승인했습니다.")}>사람 승인</button><button className="secondary-button" disabled={working} onClick={()=>act("/api/discovery/approve",{kind:"single",id:x.id,status:"sourcing"},"소싱 단계로 이동했습니다.")}>소싱 이동</button><button className="secondary-button" disabled={working} onClick={()=>act("/api/discovery/approve",{kind:"single",id:x.id,status:"rejected"},"후보를 제외했습니다.")}>제외</button></div></div></article>):<p>시장 데이터를 수집한 뒤 ‘AI 의사결정 실행’을 누르세요.</p>}</div></section>
<section className="panel"><div className="section-heading"><div><h2>AI 세트·묶음상품 추천</h2><p>구매 편의·조합 시너지·차별화·마진·위험을 함께 평가합니다.</p></div></div><div className="bundle-grid">{bundles.length?bundles.map(x=><article className="bundle-card" key={x.id}><div className="bundle-head"><span className={`decision-badge ${x.decision_action}`}>{labels[x.decision_action]}</span><span className="grade grade-A">{Math.round(x.decision_score)}</span><div><h3>{x.bundle_name}</h3><p>{x.status} · 신뢰도 {x.confidence}%</p></div></div><div className="bundle-items">{(x.ai_bundle_items??[]).map((i,k)=><span key={k}>{i.role}: {i.market_products?.title} × {i.quantity}</span>)}</div><div className="score-pills"><span>시너지 {Math.round(x.synergy_score)}</span><span>편의 {Math.round(x.convenience_score)}</span><span>차별화 {Math.round(x.differentiation_score)}</span><span>마진 {Math.round(x.margin_score)}</span><span>위험 {Math.round(x.risk_score)}</span></div><p>{x.recommendation_reason}</p><div className="card-actions"><button disabled={working} onClick={()=>act("/api/discovery/approve",{kind:"bundle",id:x.id,status:"approved"},"묶음상품 후보를 승인했습니다.")}>승인</button><button className="secondary-button" disabled={working} onClick={()=>act("/api/discovery/approve",{kind:"bundle",id:x.id,status:"sourcing"},"묶음상품을 소싱 단계로 이동했습니다.")}>소싱 이동</button></div></article>):<p>의사결정 실행 시 조합 후보가 만들어집니다.</p>}</div></section>
<section className="panel architecture-panel"><h2>v9.6 의사결정 흐름</h2><div className="pipeline"><span>시장 Feature</span><b>→</b><span>Decision Score</span><b>→</b><span>추천·검토·보류·제외</span><b>→</b><span>설명·위험 근거</span><b>→</b><span>사람 승인</span><b>→</b><span>Supplier·Workflow</span></div></section></main>}
