-- Sprint B-0 canonical pre-003 baseline.
-- Source: supabase/recovery-sources/products-baseline.sql
-- Source SHA-256: 24c6900c0a46d78679d66f58b300101ab89018e533c4324f0232f77ec1bd6f05
-- Transformation: preserve table schema; omit the source RLS enablement and
-- permissive anon policies. RLS/auth implementation is outside this approved
-- Database Baseline change and requires its own high-risk scope.

create table if not exists public.products (
  id bigint generated by default as identity primary key,

  product_no text not null unique,
  keyword text,

  title text not null,
  thumbnail text,
  product_url text,

  supply_price integer not null default 0,
  minimum_order_quantity integer not null default 1,
  initial_purchase_amount integer not null default 0,

  estimated_sale_price integer not null default 0,
  marketplace_fee integer not null default 0,
  advertising_cost integer not null default 0,
  logistics_cost integer not null default 0,
  return_reserve integer not null default 0,

  estimated_profit integer not null default 0,
  margin_rate numeric(6, 2) not null default 0,
  break_even_sale_price integer not null default 0,

  basic_score integer not null default 0,
  recommendation text,

  seller_id text,
  seller_name text,

  available_on_domeggook boolean not null default false,
  supply_available boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
