-- Gonggamline AI v5.0 Market Intelligence Engine
-- Run after existing v3/v4 migrations. Additive migration only.
create extension if not exists pgcrypto;

create table if not exists public.market_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null unique,
  category text,
  priority integer not null default 50 check (priority between 0 and 100),
  collection_status text not null default 'active' check (collection_status in ('active','paused','cooldown','blocked')),
  collection_interval_minutes integer not null default 720 check (collection_interval_minutes >= 60),
  last_collected_at timestamptz,
  next_collection_at timestamptz,
  result_count integer,
  demand_score numeric(5,2),
  competition_score numeric(5,2),
  opportunity_score numeric(5,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_products (
  id bigint generated by default as identity primary key,
  source text not null,
  external_product_id text not null,
  vendor_item_id text,
  product_url text,
  title text not null,
  brand text,
  seller_name text,
  category text,
  thumbnail_url text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source, external_product_id)
);

create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  market_keyword_id bigint references public.market_keywords(id) on delete set null,
  observed_at timestamptz not null default now(),
  rank integer,
  is_ad boolean,
  price numeric(14,2),
  list_price numeric(14,2),
  rating numeric(3,2),
  review_count integer,
  rocket_type text,
  is_sold_out boolean,
  delivery_days integer,
  option_count integer,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists market_snapshots_product_time_idx on public.market_snapshots(market_product_id, observed_at desc);
create index if not exists market_snapshots_keyword_time_idx on public.market_snapshots(market_keyword_id, observed_at desc);

create table if not exists public.market_collection_runs (
  id bigint generated by default as identity primary key,
  collector text not null,
  keyword_id bigint references public.market_keywords(id) on delete set null,
  status text not null check (status in ('started','success','partial','failed','blocked','cooldown')),
  requested_count integer not null default 0,
  saved_count integer not null default 0,
  http_status integer,
  failure_count integer not null default 0,
  cooldown_until timestamptz,
  robots_policy_state text,
  terms_review_status text not null default 'pending',
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.market_signals (
  id bigint generated by default as identity primary key,
  market_product_id bigint references public.market_products(id) on delete cascade,
  market_keyword_id bigint references public.market_keywords(id) on delete cascade,
  signal_type text not null,
  severity text not null default 'medium' check (severity in ('low','medium','high')),
  title text not null,
  evidence jsonb not null default '{}'::jsonb,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists public.market_estimates (
  id bigint generated by default as identity primary key,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  period_start date not null,
  period_end date not null,
  estimated_units_low integer not null default 0,
  estimated_units_base integer not null default 0,
  estimated_units_high integer not null default 0,
  estimated_sales_low numeric(14,2) not null default 0,
  estimated_sales_base numeric(14,2) not null default 0,
  estimated_sales_high numeric(14,2) not null default 0,
  confidence integer not null default 0 check (confidence between 0 and 100),
  model_version text not null default 'mie-heuristic-v1',
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.market_model_feedback (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  market_product_id bigint references public.market_products(id) on delete set null,
  estimate_id bigint references public.market_estimates(id) on delete set null,
  actual_units integer,
  actual_sales numeric(14,2),
  actual_ad_spend numeric(14,2),
  actual_returns integer,
  feedback_period_start date not null,
  feedback_period_end date not null,
  created_at timestamptz not null default now()
);

alter table public.market_keywords enable row level security;
alter table public.market_products enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.market_collection_runs enable row level security;
alter table public.market_signals enable row level security;
alter table public.market_estimates enable row level security;
alter table public.market_model_feedback enable row level security;

-- Development policy matching the existing dev RLS approach. Tighten before production.
do $$ begin
  create policy "dev_market_keywords_all" on public.market_keywords for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_products_all" on public.market_products for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_snapshots_all" on public.market_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_collection_runs_all" on public.market_collection_runs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_signals_all" on public.market_signals for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_estimates_all" on public.market_estimates for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_model_feedback_all" on public.market_model_feedback for all using (true) with check (true); exception when duplicate_object then null; end $$;
