-- Gonggamline AI v5.1 Market Intelligence Analytics
-- Run after 005_market_intelligence_engine.sql. Additive and idempotent.

create table if not exists public.market_product_metrics (
  market_product_id bigint primary key references public.market_products(id) on delete cascade,
  snapshot_count integer not null default 0,
  observation_days integer not null default 0,
  latest_price numeric(14,2),
  price_change_7d_pct numeric(8,2),
  latest_review_count integer,
  review_delta_7d integer not null default 0,
  review_delta_30d integer not null default 0,
  average_rank_7d numeric(8,2),
  rank_change_7d integer,
  stockout_count_30d integer not null default 0,
  demand_score numeric(5,2) not null default 0,
  growth_score numeric(5,2) not null default 0,
  stability_score numeric(5,2) not null default 0,
  competition_score numeric(5,2) not null default 0,
  opportunity_score numeric(5,2) not null default 0,
  confidence integer not null default 0 check (confidence between 0 and 100),
  estimated_units_low integer not null default 0,
  estimated_units_base integer not null default 0,
  estimated_units_high integer not null default 0,
  recommendation_grade text not null default 'D' check (recommendation_grade in ('S','A','B','C','D')),
  recommendation_reason text,
  analyzed_at timestamptz not null default now(),
  model_version text not null default 'mie-heuristic-v2'
);

create table if not exists public.market_analysis_runs (
  id bigint generated by default as identity primary key,
  status text not null check (status in ('started','success','partial','failed')),
  requested_products integer not null default 0,
  analyzed_products integer not null default 0,
  signals_created integer not null default 0,
  estimates_created integer not null default 0,
  model_version text not null default 'mie-heuristic-v2',
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create index if not exists market_product_metrics_opportunity_idx
  on public.market_product_metrics(opportunity_score desc, confidence desc);
create index if not exists market_signals_unresolved_idx
  on public.market_signals(detected_at desc) where resolved_at is null;
create index if not exists market_estimates_product_created_idx
  on public.market_estimates(market_product_id, created_at desc);

alter table public.market_product_metrics enable row level security;
alter table public.market_analysis_runs enable row level security;

do $$ begin
  create policy "dev_market_product_metrics_all" on public.market_product_metrics
  for all using (true) with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "dev_market_analysis_runs_all" on public.market_analysis_runs
  for all using (true) with check (true);
exception when duplicate_object then null; end $$;
