-- Gonggamline AI v6.0 Market Intelligence Orchestration
-- Run after 006_market_intelligence_analytics.sql. Additive and idempotent.

create table if not exists public.market_collectors (
  id bigint generated by default as identity primary key,
  collector_key text not null unique,
  name text not null,
  source_type text not null check (source_type in ('official_api','public_observation','manual','internal','demo')),
  status text not null default 'ready' check (status in ('ready','disabled','cooldown','blocked','error')),
  supports_automatic boolean not null default false,
  configuration jsonb not null default '{}'::jsonb,
  last_run_at timestamptz,
  last_success_at timestamptz,
  cooldown_until timestamptz,
  failure_count integer not null default 0,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_collection_jobs (
  id bigint generated by default as identity primary key,
  collector_key text not null references public.market_collectors(collector_key) on delete cascade,
  market_keyword_id bigint references public.market_keywords(id) on delete cascade,
  status text not null default 'active' check (status in ('active','paused','running','cooldown','failed')),
  priority integer not null default 50 check (priority between 0 and 100),
  interval_minutes integer not null default 720 check (interval_minutes >= 60),
  next_run_at timestamptz not null default now(),
  last_run_at timestamptz,
  last_result jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(collector_key, market_keyword_id)
);

create table if not exists public.market_ai_decisions (
  id bigint generated by default as identity primary key,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  decision_type text not null default 'product_entry',
  recommendation text not null check (recommendation in ('strong_buy','buy','watch','avoid','insufficient_data')),
  score numeric(5,2) not null default 0,
  confidence integer not null default 0 check (confidence between 0 and 100),
  rationale text not null,
  evidence jsonb not null default '{}'::jsonb,
  model_version text not null default 'mie-decision-v1',
  created_at timestamptz not null default now()
);

create table if not exists public.market_product_links (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  match_method text not null default 'manual' check (match_method in ('manual','external_id','title_similarity','ai')),
  match_confidence integer not null default 100 check (match_confidence between 0 and 100),
  created_at timestamptz not null default now(),
  unique(product_id, market_product_id)
);

create index if not exists market_collection_jobs_due_idx on public.market_collection_jobs(status, next_run_at, priority desc);
create index if not exists market_ai_decisions_product_created_idx on public.market_ai_decisions(market_product_id, created_at desc);

insert into public.market_collectors (collector_key, name, source_type, supports_automatic, status)
values
  ('manual-input', '수동 관측 입력', 'manual', false, 'ready'),
  ('demo-generator', 'DEMO 시계열 생성기', 'demo', true, 'ready'),
  ('internal-sales', '내부 실매출 피드백', 'internal', true, 'ready'),
  ('official-api-adapter', '공식 API 어댑터', 'official_api', true, 'disabled'),
  ('public-observation-adapter', '공개 페이지 관측 어댑터', 'public_observation', true, 'disabled')
on conflict (collector_key) do update set
  name = excluded.name,
  source_type = excluded.source_type,
  supports_automatic = excluded.supports_automatic,
  updated_at = now();

alter table public.market_collectors enable row level security;
alter table public.market_collection_jobs enable row level security;
alter table public.market_ai_decisions enable row level security;
alter table public.market_product_links enable row level security;

do $$ begin create policy "dev_market_collectors_all" on public.market_collectors for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_collection_jobs_all" on public.market_collection_jobs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_ai_decisions_all" on public.market_ai_decisions for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_product_links_all" on public.market_product_links for all using (true) with check (true); exception when duplicate_object then null; end $$;
