-- Gonggamline AI v7.0 Market Data Warehouse + Feature Engine
-- Run after 007_market_intelligence_orchestration.sql. Additive and idempotent.

alter table public.market_product_metrics
  add column if not exists price_volatility_30d numeric(8,3),
  add column if not exists rank_volatility_30d numeric(8,3),
  add column if not exists review_velocity_7d numeric(10,3),
  add column if not exists data_completeness_score numeric(5,2) not null default 0,
  add column if not exists supply_score numeric(5,2) not null default 50,
  add column if not exists ad_burden_score numeric(5,2) not null default 50,
  add column if not exists entry_difficulty_score numeric(5,2) not null default 50,
  add column if not exists feature_version text not null default 'mie-features-v1',
  add column if not exists score_explanation jsonb not null default '{}'::jsonb;

create table if not exists public.market_feature_snapshots (
  id bigint generated by default as identity primary key,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  calculated_at timestamptz not null default now(),
  feature_version text not null default 'mie-features-v1',
  observation_days integer not null default 0,
  snapshot_count integer not null default 0,
  review_velocity_7d numeric(10,3),
  review_growth_30d integer,
  price_change_7d_pct numeric(10,3),
  price_volatility_30d numeric(10,3),
  rank_change_7d numeric(10,3),
  rank_volatility_30d numeric(10,3),
  stockout_count_30d integer,
  ad_ratio_30d numeric(8,4),
  data_completeness_score numeric(5,2),
  demand_score numeric(5,2),
  growth_score numeric(5,2),
  stability_score numeric(5,2),
  competition_score numeric(5,2),
  supply_score numeric(5,2),
  ad_burden_score numeric(5,2),
  entry_difficulty_score numeric(5,2),
  opportunity_score numeric(5,2),
  confidence integer,
  evidence jsonb not null default '{}'::jsonb
);

create table if not exists public.market_feedback_events (
  id bigint generated by default as identity primary key,
  market_product_id bigint references public.market_products(id) on delete set null,
  product_id bigint references public.products(id) on delete set null,
  event_type text not null check (event_type in ('registered','sale','return','ad_spend','stockout','manual_rating')),
  event_at timestamptz not null default now(),
  quantity integer,
  amount numeric(14,2),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists market_feature_snapshots_product_time_idx on public.market_feature_snapshots(market_product_id, calculated_at desc);
create index if not exists market_feedback_events_product_time_idx on public.market_feedback_events(market_product_id, event_at desc);

alter table public.market_feature_snapshots enable row level security;
alter table public.market_feedback_events enable row level security;
do $$ begin create policy "dev_market_feature_snapshots_all" on public.market_feature_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_market_feedback_events_all" on public.market_feedback_events for all using (true) with check (true); exception when duplicate_object then null; end $$;
