-- Gonggamline AI v8.0 AI Product Discovery + Bundle Intelligence
-- Run after 008_market_data_warehouse.sql. Additive and idempotent.

create table if not exists public.ai_product_recommendations (
  id bigint generated by default as identity primary key,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  recommendation_type text not null default 'single' check (recommendation_type in ('single','set','bundle')),
  status text not null default 'candidate' check (status in ('candidate','reviewing','approved','rejected','sourcing')),
  ai_score numeric(5,2) not null default 0,
  market_score numeric(5,2) not null default 0,
  growth_score numeric(5,2) not null default 0,
  competition_score numeric(5,2) not null default 50,
  risk_score numeric(5,2) not null default 50,
  profit_score numeric(5,2) not null default 50,
  confidence integer not null default 0,
  estimated_units_low integer not null default 0,
  estimated_units_high integer not null default 0,
  target_sale_price numeric(14,2),
  target_cost_price numeric(14,2),
  target_margin_rate numeric(8,3),
  recommendation_reason text,
  evidence jsonb not null default '{}'::jsonb,
  model_version text not null default 'discovery-v1',
  generated_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique(market_product_id, recommendation_type)
);

create table if not exists public.ai_bundle_recommendations (
  id bigint generated by default as identity primary key,
  bundle_name text not null,
  bundle_type text not null default 'bundle' check (bundle_type in ('set','bundle','multipack')),
  keyword text,
  category text,
  status text not null default 'candidate' check (status in ('candidate','reviewing','approved','rejected','sourcing')),
  ai_score numeric(5,2) not null default 0,
  synergy_score numeric(5,2) not null default 0,
  convenience_score numeric(5,2) not null default 0,
  differentiation_score numeric(5,2) not null default 0,
  margin_score numeric(5,2) not null default 50,
  confidence integer not null default 0,
  target_sale_price numeric(14,2),
  target_cost_price numeric(14,2),
  target_margin_rate numeric(8,3),
  recommendation_reason text,
  evidence jsonb not null default '{}'::jsonb,
  generated_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.ai_bundle_items (
  id bigint generated by default as identity primary key,
  bundle_id bigint not null references public.ai_bundle_recommendations(id) on delete cascade,
  market_product_id bigint not null references public.market_products(id) on delete cascade,
  role text not null default 'component' check (role in ('anchor','complement','consumable','accessory','component')),
  quantity integer not null default 1 check (quantity > 0),
  item_order integer not null default 0,
  unique(bundle_id, market_product_id)
);

create index if not exists ai_product_recommendations_score_idx on public.ai_product_recommendations(ai_score desc, generated_at desc);
create index if not exists ai_bundle_recommendations_score_idx on public.ai_bundle_recommendations(ai_score desc, generated_at desc);
create index if not exists ai_bundle_items_bundle_idx on public.ai_bundle_items(bundle_id, item_order);

alter table public.ai_product_recommendations enable row level security;
alter table public.ai_bundle_recommendations enable row level security;
alter table public.ai_bundle_items enable row level security;
do $$ begin create policy "dev_ai_product_recommendations_all" on public.ai_product_recommendations for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_ai_bundle_recommendations_all" on public.ai_bundle_recommendations for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_ai_bundle_items_all" on public.ai_bundle_items for all using (true) with check (true); exception when duplicate_object then null; end $$;
