-- v8.2 Supplier Intelligence Engine
create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  channel text not null check (channel in ('domestic_wholesale','consignment','oem','import','manual')),
  contact_name text,
  contact_email text,
  contact_phone text,
  website_url text,
  country_code text not null default 'KR',
  status text not null default 'active' check (status in ('active','paused','blocked')),
  reliability_score numeric(5,2) not null default 50,
  memo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.supplier_quotes (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  discovery_recommendation_id bigint references public.ai_product_recommendations(id) on delete set null,
  bundle_recommendation_id bigint references public.ai_bundle_recommendations(id) on delete set null,
  product_name text not null,
  supplier_sku text,
  currency text not null default 'KRW' check (currency in ('KRW','USD','CNY')),
  exchange_rate numeric(14,4) not null default 1,
  unit_cost numeric(14,2) not null default 0,
  moq integer not null default 1 check (moq > 0),
  sample_cost numeric(14,2) not null default 0,
  domestic_shipping_total numeric(14,2) not null default 0,
  international_shipping_total numeric(14,2) not null default 0,
  customs_total numeric(14,2) not null default 0,
  vat_total numeric(14,2) not null default 0,
  inspection_total numeric(14,2) not null default 0,
  packaging_total numeric(14,2) not null default 0,
  labeling_total numeric(14,2) not null default 0,
  three_pl_inbound_total numeric(14,2) not null default 0,
  three_pl_storage_per_unit numeric(14,2) not null default 0,
  three_pl_outbound_per_unit numeric(14,2) not null default 0,
  coupang_fee_rate numeric(7,4) not null default 10.8,
  expected_return_rate numeric(7,4) not null default 3,
  lead_time_days integer not null default 7,
  valid_until date,
  status text not null default 'draft' check (status in ('draft','requested','received','selected','rejected','expired')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((discovery_recommendation_id is not null) or (bundle_recommendation_id is not null))
);

create table if not exists public.sourcing_decisions (
  id bigint generated by default as identity primary key,
  supplier_quote_id bigint not null references public.supplier_quotes(id) on delete cascade,
  target_selling_price numeric(14,2) not null,
  landed_unit_cost numeric(14,2) not null,
  coupang_fee_per_unit numeric(14,2) not null default 0,
  expected_return_cost_per_unit numeric(14,2) not null default 0,
  expected_profit_per_unit numeric(14,2) not null,
  expected_margin_rate numeric(7,4) not null,
  initial_purchase_amount numeric(14,2) not null,
  working_capital_days integer not null default 0,
  decision text not null check (decision in ('approve','review','reject')),
  score numeric(5,2) not null default 0,
  reasons jsonb not null default '[]'::jsonb,
  calculated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_supplier_quotes_supplier on public.supplier_quotes(supplier_id);
create index if not exists idx_supplier_quotes_single on public.supplier_quotes(discovery_recommendation_id);
create index if not exists idx_supplier_quotes_bundle on public.supplier_quotes(bundle_recommendation_id);
create index if not exists idx_sourcing_decisions_quote on public.sourcing_decisions(supplier_quote_id, calculated_at desc);

alter table public.suppliers enable row level security;
alter table public.supplier_quotes enable row level security;
alter table public.sourcing_decisions enable row level security;

-- Development policy. Replace with authenticated owner policies before production.
do $$ begin
  create policy "dev suppliers all" on public.suppliers for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "dev supplier quotes all" on public.supplier_quotes for all using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "dev sourcing decisions all" on public.sourcing_decisions for all using (true) with check (true);
exception when duplicate_object then null; end $$;
