-- v8.3 Domestic Procurement + Commerce Workflow Engine
create table if not exists public.domestic_supplier_products (
  id bigint generated by default as identity primary key,
  supplier_id bigint not null references public.suppliers(id) on delete cascade,
  discovery_recommendation_id bigint references public.ai_product_recommendations(id) on delete set null,
  bundle_recommendation_id bigint references public.ai_bundle_recommendations(id) on delete set null,
  provider text not null default 'domeggook' check (provider in ('domeggook','domeme','ownerclan','manual')),
  provider_product_id text not null,
  provider_product_url text,
  provider_product_name text not null,
  provider_sku text,
  minimum_order_quantity integer not null default 1 check (minimum_order_quantity > 0),
  current_unit_cost numeric(14,2) not null default 0,
  stock_status text not null default 'unknown' check (stock_status in ('in_stock','low_stock','out_of_stock','unknown')),
  mapping_status text not null default 'active' check (mapping_status in ('active','paused','rejected')),
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((discovery_recommendation_id is not null) or (bundle_recommendation_id is not null))
);

create table if not exists public.procurement_orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  supplier_id bigint not null references public.suppliers(id) on delete restrict,
  supplier_quote_id bigint not null references public.supplier_quotes(id) on delete restrict,
  supplier_product_mapping_id bigint references public.domestic_supplier_products(id) on delete set null,
  discovery_recommendation_id bigint references public.ai_product_recommendations(id) on delete set null,
  bundle_recommendation_id bigint references public.ai_bundle_recommendations(id) on delete set null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_cost numeric(14,2) not null,
  goods_amount numeric(14,2) not null,
  shipping_amount numeric(14,2) not null default 0,
  packaging_amount numeric(14,2) not null default 0,
  three_pl_inbound_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null,
  expected_inbound_date date,
  status text not null default 'draft' check (status in ('draft','approved','ordered','supplier_confirmed','inbound_planned','in_transit','received','cancelled')),
  procurement_score numeric(5,2) not null default 0,
  approval_reasons jsonb not null default '[]'::jsonb,
  supplier_order_reference text,
  notes text,
  approved_at timestamptz,
  ordered_at timestamptz,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.three_pl_inbound_plans (
  id bigint generated by default as identity primary key,
  procurement_order_id bigint not null references public.procurement_orders(id) on delete cascade,
  warehouse_name text not null,
  warehouse_code text,
  inbound_reference text,
  expected_inbound_date date,
  expected_quantity integer not null check (expected_quantity > 0),
  received_quantity integer not null default 0 check (received_quantity >= 0),
  status text not null default 'planned' check (status in ('planned','booked','in_transit','partially_received','received','cancelled')),
  receiving_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.commerce_workflows (
  id bigint generated by default as identity primary key,
  discovery_recommendation_id bigint references public.ai_product_recommendations(id) on delete set null,
  bundle_recommendation_id bigint references public.ai_bundle_recommendations(id) on delete set null,
  procurement_order_id bigint references public.procurement_orders(id) on delete set null,
  workflow_name text not null,
  current_stage text not null default 'market_discovered' check (current_stage in ('market_discovered','ai_recommended','human_approved','supplier_mapped','quote_selected','purchase_approved','purchase_ordered','three_pl_inbound','listing_ready','coupang_registered','selling','learning')),
  status text not null default 'active' check (status in ('active','blocked','completed','cancelled')),
  blocked_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check ((discovery_recommendation_id is not null) or (bundle_recommendation_id is not null))
);

create table if not exists public.commerce_timeline_events (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  stage text not null,
  event_type text not null,
  title text not null,
  detail jsonb not null default '{}'::jsonb,
  actor text not null default 'system',
  created_at timestamptz not null default now()
);

create index if not exists idx_domestic_supplier_products_candidate on public.domestic_supplier_products(discovery_recommendation_id, bundle_recommendation_id);
create index if not exists idx_procurement_orders_status on public.procurement_orders(status, created_at desc);
create index if not exists idx_inbound_plans_order on public.three_pl_inbound_plans(procurement_order_id);
create index if not exists idx_workflows_stage on public.commerce_workflows(current_stage, updated_at desc);
create index if not exists idx_timeline_workflow on public.commerce_timeline_events(workflow_id, created_at desc);

alter table public.domestic_supplier_products enable row level security;
alter table public.procurement_orders enable row level security;
alter table public.three_pl_inbound_plans enable row level security;
alter table public.commerce_workflows enable row level security;
alter table public.commerce_timeline_events enable row level security;

do $$ begin create policy "dev domestic supplier products all" on public.domestic_supplier_products for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev procurement orders all" on public.procurement_orders for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev inbound plans all" on public.three_pl_inbound_plans for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev commerce workflows all" on public.commerce_workflows for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev commerce timeline all" on public.commerce_timeline_events for all using (true) with check (true); exception when duplicate_object then null; end $$;
