-- v8.4 Product Workspace + Listing AI Draft Engine
-- Run after 011_procurement_workflow_engine.sql. Additive and idempotent.

create table if not exists public.listing_drafts (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  procurement_order_id bigint references public.procurement_orders(id) on delete set null,
  discovery_recommendation_id bigint references public.ai_product_recommendations(id) on delete set null,
  bundle_recommendation_id bigint references public.ai_bundle_recommendations(id) on delete set null,
  listing_type text not null default 'single' check (listing_type in ('single','set','bundle','multipack')),
  status text not null default 'generated' check (status in ('draft','generated','reviewing','approved','rejected','registered')),
  product_name text not null,
  brand_name text,
  category_name text,
  coupang_title text not null,
  search_keywords text[] not null default '{}',
  option_structure jsonb not null default '[]'::jsonb,
  selling_points jsonb not null default '[]'::jsonb,
  detail_sections jsonb not null default '[]'::jsonb,
  faq jsonb not null default '[]'::jsonb,
  thumbnail_brief text,
  shipping_notice text,
  return_notice text,
  compliance_checklist jsonb not null default '[]'::jsonb,
  coupang_payload jsonb not null default '{}'::jsonb,
  generation_input jsonb not null default '{}'::jsonb,
  model_version text not null default 'listing-rule-v1',
  revision integer not null default 1,
  approved_at timestamptz,
  registered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_draft_revisions (
  id bigint generated by default as identity primary key,
  listing_draft_id bigint not null references public.listing_drafts(id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  change_note text,
  actor text not null default 'system',
  created_at timestamptz not null default now(),
  unique(listing_draft_id, revision)
);

alter table public.commerce_workflows add column if not exists listing_draft_id bigint references public.listing_drafts(id) on delete set null;

create index if not exists idx_listing_drafts_workflow on public.listing_drafts(workflow_id, created_at desc);
create index if not exists idx_listing_drafts_status on public.listing_drafts(status, updated_at desc);
create index if not exists idx_listing_revisions_draft on public.listing_draft_revisions(listing_draft_id, revision desc);

alter table public.listing_drafts enable row level security;
alter table public.listing_draft_revisions enable row level security;
do $$ begin create policy "dev listing drafts all" on public.listing_drafts for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev listing revisions all" on public.listing_draft_revisions for all using (true) with check (true); exception when duplicate_object then null; end $$;
