-- v9.0 Commerce Workflow Integration Engine
-- Run after 012_product_workspace_listing_ai.sql. Additive and idempotent.

alter table public.commerce_workflows add column if not exists workflow_code text;
alter table public.commerce_workflows add column if not exists lifecycle_type text not null default 'single';
alter table public.commerce_workflows add column if not exists stage_version integer not null default 1;
alter table public.commerce_workflows add column if not exists last_transition_at timestamptz;
alter table public.commerce_workflows add column if not exists metadata jsonb not null default '{}'::jsonb;

update public.commerce_workflows
set workflow_code = 'WF-' || to_char(created_at, 'YYYYMMDD') || '-' || lpad(id::text, 6, '0')
where workflow_code is null;

create unique index if not exists idx_commerce_workflows_code on public.commerce_workflows(workflow_code);

create table if not exists public.workflow_transitions (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  from_stage text,
  to_stage text not null,
  trigger_type text not null default 'system',
  trigger_source text,
  idempotency_key text,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  actor text not null default 'system',
  created_at timestamptz not null default now()
);

create unique index if not exists idx_workflow_transitions_idempotency
  on public.workflow_transitions(idempotency_key)
  where idempotency_key is not null;
create index if not exists idx_workflow_transitions_workflow
  on public.workflow_transitions(workflow_id, created_at desc);

create table if not exists public.workflow_tasks (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  stage text not null,
  task_type text not null,
  title text not null,
  status text not null default 'open' check (status in ('open','in_progress','done','cancelled','blocked')),
  priority integer not null default 50 check (priority between 0 and 100),
  assignee text,
  due_at timestamptz,
  blocking_reason text,
  payload jsonb not null default '{}'::jsonb,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(workflow_id, stage, task_type)
);

create index if not exists idx_workflow_tasks_queue
  on public.workflow_tasks(status, priority desc, due_at asc nulls last);

create table if not exists public.workflow_outbox_events (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  event_name text not null,
  destination text not null default 'internal',
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','sent','failed','cancelled')),
  attempt_count integer not null default 0,
  available_at timestamptz not null default now(),
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);

create index if not exists idx_workflow_outbox_pending
  on public.workflow_outbox_events(status, available_at);

alter table public.workflow_transitions enable row level security;
alter table public.workflow_tasks enable row level security;
alter table public.workflow_outbox_events enable row level security;

do $$ begin create policy "dev workflow transitions all" on public.workflow_transitions for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev workflow tasks all" on public.workflow_tasks for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev workflow outbox all" on public.workflow_outbox_events for all using (true) with check (true); exception when duplicate_object then null; end $$;
