-- v9.5 Coupang Seller Registration Operations Engine
-- Run after 013_commerce_workflow_integration.sql. Additive and idempotent.

create table if not exists public.coupang_registration_jobs (
  id bigint generated by default as identity primary key,
  workflow_id bigint not null references public.commerce_workflows(id) on delete cascade,
  listing_draft_id bigint not null references public.listing_drafts(id) on delete cascade,
  job_code text not null,
  status text not null default 'queued' check (status in ('queued','validating','validation_failed','ready','submitting','submitted','registered','failed','cancelled')),
  mode text not null default 'validate' check (mode in ('validate','live')),
  payload_snapshot jsonb not null default '{}'::jsonb,
  validation_issues jsonb not null default '[]'::jsonb,
  seller_product_id text,
  vendor_item_ids jsonb not null default '[]'::jsonb,
  coupang_status text,
  registration_response jsonb,
  last_error text,
  attempt_count integer not null default 0,
  next_retry_at timestamptz,
  submitted_at timestamptz,
  registered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(listing_draft_id)
);

create unique index if not exists idx_coupang_jobs_code on public.coupang_registration_jobs(job_code);
create index if not exists idx_coupang_jobs_queue on public.coupang_registration_jobs(status, updated_at desc);
create index if not exists idx_coupang_jobs_workflow on public.coupang_registration_jobs(workflow_id, updated_at desc);

create table if not exists public.coupang_registration_attempts (
  id bigint generated by default as identity primary key,
  job_id bigint not null references public.coupang_registration_jobs(id) on delete cascade,
  attempt_no integer not null,
  action text not null check (action in ('validate','submit','retry','cancel','sync')),
  request_payload jsonb not null default '{}'::jsonb,
  response_status integer,
  response_payload jsonb,
  success boolean not null default false,
  error_message text,
  duration_ms integer,
  created_at timestamptz not null default now(),
  unique(job_id, attempt_no)
);

create index if not exists idx_coupang_attempts_job on public.coupang_registration_attempts(job_id, created_at desc);

create table if not exists public.coupang_seller_product_snapshots (
  id bigint generated by default as identity primary key,
  seller_product_id text not null,
  seller_product_name text,
  status_name text,
  brand text,
  registration_type text,
  raw_payload jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null default now()
);

create index if not exists idx_coupang_product_snapshots_product on public.coupang_seller_product_snapshots(seller_product_id, observed_at desc);

alter table public.commerce_workflows add column if not exists coupang_registration_job_id bigint references public.coupang_registration_jobs(id) on delete set null;

alter table public.coupang_registration_jobs enable row level security;
alter table public.coupang_registration_attempts enable row level security;
alter table public.coupang_seller_product_snapshots enable row level security;

do $$ begin create policy "dev coupang jobs all" on public.coupang_registration_jobs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev coupang attempts all" on public.coupang_registration_attempts for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev coupang snapshots all" on public.coupang_seller_product_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;
