-- Gonggamline AI v9.6 AI Decision Engine
-- Run after 014_coupang_seller_engine.sql. Additive and idempotent.

create table if not exists public.ai_decision_runs (
  id bigint generated by default as identity primary key,
  run_type text not null default 'discovery',
  status text not null default 'queued' check (status in ('queued','running','completed','failed')),
  model_version text not null default 'decision-v2',
  input_limit integer not null default 100,
  processed_count integer not null default 0,
  recommendation_count integer not null default 0,
  bundle_count integer not null default 0,
  decision_summary jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.ai_product_recommendations add column if not exists decision_run_id bigint references public.ai_decision_runs(id) on delete set null;
alter table public.ai_product_recommendations add column if not exists decision_score numeric(5,2) not null default 0;
alter table public.ai_product_recommendations add column if not exists decision_action text not null default 'review';
alter table public.ai_product_recommendations add column if not exists supply_score numeric(5,2) not null default 50;
alter table public.ai_product_recommendations add column if not exists season_score numeric(5,2) not null default 50;
alter table public.ai_product_recommendations add column if not exists risk_explanation text;

alter table public.ai_bundle_recommendations add column if not exists decision_run_id bigint references public.ai_decision_runs(id) on delete set null;
alter table public.ai_bundle_recommendations add column if not exists decision_score numeric(5,2) not null default 0;
alter table public.ai_bundle_recommendations add column if not exists decision_action text not null default 'review';
alter table public.ai_bundle_recommendations add column if not exists risk_score numeric(5,2) not null default 50;

do $$ begin
  alter table public.ai_product_recommendations add constraint ai_product_recommendations_decision_action_check check (decision_action in ('approve','review','hold','reject'));
exception when duplicate_object then null; end $$;
do $$ begin
  alter table public.ai_bundle_recommendations add constraint ai_bundle_recommendations_decision_action_check check (decision_action in ('approve','review','hold','reject'));
exception when duplicate_object then null; end $$;

create index if not exists ai_decision_runs_started_idx on public.ai_decision_runs(started_at desc);
create index if not exists ai_product_recommendations_decision_idx on public.ai_product_recommendations(decision_action, decision_score desc);
create index if not exists ai_bundle_recommendations_decision_idx on public.ai_bundle_recommendations(decision_action, decision_score desc);

alter table public.ai_decision_runs enable row level security;
do $$ begin create policy "dev_ai_decision_runs_all" on public.ai_decision_runs for all using (true) with check (true); exception when duplicate_object then null; end $$;
