-- Gonggamline AI v10.0 · AI Company OS Foundation
-- Run after 015_ai_decision_engine.sql. Additive and idempotent.

create table if not exists public.ai_workers (
  id bigint generated by default as identity primary key,
  worker_code text not null unique,
  worker_name text not null,
  role text not null,
  status text not null default 'idle' check (status in ('idle','working','waiting_approval','blocked','disabled')),
  current_mission text,
  current_job text,
  performance_score numeric(5,2) not null default 0,
  automation_level integer not null default 1 check (automation_level between 0 and 5),
  last_activity_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.system_releases (
  id bigint generated by default as identity primary key,
  version text not null unique,
  release_name text not null,
  status text not null default 'planned' check (status in ('planned','building','verifying','released','rolled_back','failed')),
  migration_name text,
  verification_summary jsonb not null default '{}'::jsonb,
  release_notes text,
  rollback_notes text,
  released_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.system_health_checks (
  id bigint generated by default as identity primary key,
  component text not null,
  status text not null check (status in ('ok','warning','error','unknown')),
  latency_ms integer,
  message text,
  detail jsonb not null default '{}'::jsonb,
  checked_at timestamptz not null default now()
);

create table if not exists public.revenue_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null unique,
  gross_revenue numeric(14,2) not null default 0,
  net_revenue numeric(14,2) not null default 0,
  contribution_profit numeric(14,2) not null default 0,
  order_count integer not null default 0,
  ad_spend numeric(14,2) not null default 0,
  active_product_count integer not null default 0,
  out_of_stock_count integer not null default 0,
  automation_rate numeric(5,2) not null default 0,
  ai_execution_rate numeric(5,2) not null default 0,
  source_detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_decision_runs add column if not exists evidence jsonb not null default '[]'::jsonb;
alter table public.ai_decision_runs add column if not exists confidence_score numeric(5,2) not null default 0;
alter table public.ai_decision_runs add column if not exists approval_status text not null default 'not_required';
alter table public.ai_decision_runs add column if not exists approved_by text;
alter table public.ai_decision_runs add column if not exists approved_at timestamptz;
alter table public.ai_decision_runs add column if not exists result_summary jsonb not null default '{}'::jsonb;
alter table public.ai_decision_runs add column if not exists learning_summary jsonb not null default '{}'::jsonb;

do $$ begin
  alter table public.ai_decision_runs add constraint ai_decision_runs_approval_status_check
  check (approval_status in ('not_required','pending','approved','rejected'));
exception when duplicate_object then null; end $$;

create index if not exists ai_workers_status_idx on public.ai_workers(status, last_activity_at desc);
create index if not exists system_releases_status_idx on public.system_releases(status, created_at desc);
create index if not exists system_health_checks_component_idx on public.system_health_checks(component, checked_at desc);
create index if not exists revenue_snapshots_date_idx on public.revenue_snapshots(snapshot_date desc);

insert into public.ai_workers (worker_code, worker_name, role, status, automation_level, metadata)
values
  ('ai-ceo','AI CEO','우선순위·위험·자본 배분 요약','idle',1,'{"kpi":["revenue","profit","cash","risk"]}'::jsonb),
  ('ai-md','AI MD','상품 후보 발굴·평가','idle',2,'{"kpi":["approval_rate","sales_rate"]}'::jsonb),
  ('ai-buyer','AI Buyer','공급사·견적·발주 제안','idle',1,'{"kpi":["landed_cost","lead_time"]}'::jsonb),
  ('ai-profit','AI Profit','예상·실제 공헌이익 계산','idle',2,'{"kpi":["calculation_accuracy","contribution_profit"]}'::jsonb),
  ('ai-content','AI Content','상품명·키워드·상세·썸네일 생성','idle',2,'{"kpi":["ctr","cvr","return_rate"]}'::jsonb),
  ('ai-marketplace','AI Marketplace','쿠팡 등록·상태 동기화','idle',1,'{"kpi":["registration_success_rate"]}'::jsonb),
  ('ai-inventory','AI Inventory','재고·재주문 제안','idle',1,'{"kpi":["stockout_days","turnover"]}'::jsonb)
on conflict (worker_code) do update set
  worker_name=excluded.worker_name, role=excluded.role, metadata=excluded.metadata, updated_at=now();

insert into public.system_releases(version, release_name, status, migration_name, release_notes, rollback_notes, released_at)
values ('10.0.0','AI Company OS Foundation','released','016_ai_company_os_foundation.sql',
'Business Core 운영 관점, Diagnostics, Worker Registry, Revenue Dashboard, Release Manager를 도입합니다.',
'애플리케이션을 v9.6 패키지로 되돌리고 016 migration으로 추가된 테이블은 데이터 보존을 위해 유지합니다.', now())
on conflict (version) do update set status='released', released_at=coalesce(public.system_releases.released_at, now()), updated_at=now();

alter table public.ai_workers enable row level security;
alter table public.system_releases enable row level security;
alter table public.system_health_checks enable row level security;
alter table public.revenue_snapshots enable row level security;
do $$ begin create policy "dev_ai_workers_all" on public.ai_workers for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_system_releases_all" on public.system_releases for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_system_health_checks_all" on public.system_health_checks for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_revenue_snapshots_all" on public.revenue_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;
