-- Gonggamline AI v10.2 · Command Center + Workflow Automation
-- Run after 016_ai_company_os_foundation.sql. Additive and idempotent.

create table if not exists public.os_command_runs (
  id bigint generated by default as identity primary key,
  command_code text not null,
  command_name text not null,
  status text not null default 'queued' check (status in ('queued','running','waiting_approval','completed','failed','cancelled')),
  requested_by text not null default 'owner',
  assigned_worker_code text references public.ai_workers(worker_code) on delete set null,
  input_payload jsonb not null default '{}'::jsonb,
  output_summary jsonb not null default '{}'::jsonb,
  error_message text,
  progress integer not null default 0 check (progress between 0 and 100),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.os_notifications (
  id bigint generated by default as identity primary key,
  severity text not null default 'info' check (severity in ('info','success','warning','error')),
  category text not null default 'system',
  title text not null,
  message text,
  action_url text,
  is_read boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists os_command_runs_queue_idx on public.os_command_runs(status, created_at desc);
create index if not exists os_command_runs_worker_idx on public.os_command_runs(assigned_worker_code, created_at desc);
create index if not exists os_notifications_unread_idx on public.os_notifications(is_read, created_at desc);

alter table public.os_command_runs enable row level security;
alter table public.os_notifications enable row level security;
do $$ begin create policy "dev_os_command_runs_all" on public.os_command_runs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_os_notifications_all" on public.os_notifications for all using (true) with check (true); exception when duplicate_object then null; end $$;

insert into public.system_releases(version, release_name, status, migration_name, release_notes, rollback_notes, released_at)
values ('10.2.0','Command Center + Workflow Automation','released','017_command_center_workflow_automation.sql',
'v10.1 Command Center와 v10.2 Workflow Automation을 통합합니다. 실행 명령, 파이프라인, 실시간 활동, Worker 작업 상태, 확장 Diagnostics를 제공합니다.',
'애플리케이션을 v10.0 패키지로 복원합니다. 017에서 생성된 테이블은 데이터 보존을 위해 유지하거나 수동 삭제할 수 있습니다.', now())
on conflict (version) do update set status='released', migration_name=excluded.migration_name, release_notes=excluded.release_notes, released_at=coalesce(public.system_releases.released_at, now()), updated_at=now();
