-- Gonggamline AI v11.0 · Autonomous Company Enterprise
-- Run after 017_command_center_workflow_automation.sql. Additive and idempotent.

create table if not exists public.ai_ceo_briefs (
  id bigint generated by default as identity primary key,
  brief_date date not null default current_date,
  headline text not null,
  executive_summary text,
  priorities jsonb not null default '[]'::jsonb,
  recommended_actions jsonb not null default '[]'::jsonb,
  risks jsonb not null default '[]'::jsonb,
  expected_revenue numeric not null default 0,
  expected_profit numeric not null default 0,
  confidence numeric not null default 0 check (confidence between 0 and 100),
  status text not null default 'draft' check (status in ('draft','review','approved','executing','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(brief_date)
);

create table if not exists public.ai_memory_events (
  id bigint generated by default as identity primary key,
  memory_type text not null default 'decision',
  subject_type text not null default 'system',
  subject_id text,
  title text not null,
  reason text,
  evidence jsonb not null default '[]'::jsonb,
  decision text,
  result text,
  learning text,
  confidence numeric not null default 0 check (confidence between 0 and 100),
  impact_score numeric not null default 0,
  tags text[] not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.knowledge_assets (
  id bigint generated by default as identity primary key,
  asset_type text not null default 'sop' check (asset_type in ('sop','prompt','experiment','success_case','failure_case','policy','playbook')),
  title text not null,
  summary text,
  content jsonb not null default '{}'::jsonb,
  status text not null default 'active' check (status in ('draft','active','archived')),
  version text not null default '1.0',
  tags text[] not null default '{}',
  usage_count integer not null default 0,
  success_rate numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.marketplace_connections (
  id bigint generated by default as identity primary key,
  marketplace_code text not null unique,
  marketplace_name text not null,
  status text not null default 'planned' check (status in ('planned','configuring','connected','warning','error','disabled')),
  automation_level integer not null default 0 check (automation_level between 0 and 5),
  product_count integer not null default 0,
  order_count integer not null default 0,
  gross_revenue numeric not null default 0,
  last_sync_at timestamptz,
  health_message text,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.profit_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null default current_date,
  gross_revenue numeric not null default 0,
  product_cost numeric not null default 0,
  marketplace_fee numeric not null default 0,
  fulfillment_cost numeric not null default 0,
  ad_spend numeric not null default 0,
  refund_cost numeric not null default 0,
  contribution_profit numeric generated always as (gross_revenue-product_cost-marketplace_fee-fulfillment_cost-ad_spend-refund_cost) stored,
  margin_rate numeric not null default 0,
  roas numeric not null default 0,
  break_even_revenue numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(snapshot_date)
);

create index if not exists ai_memory_events_subject_idx on public.ai_memory_events(subject_type, subject_id, created_at desc);
create index if not exists knowledge_assets_type_idx on public.knowledge_assets(asset_type, status, updated_at desc);
create index if not exists ai_ceo_briefs_date_idx on public.ai_ceo_briefs(brief_date desc);
create index if not exists marketplace_connections_status_idx on public.marketplace_connections(status, marketplace_code);

alter table public.ai_ceo_briefs enable row level security;
alter table public.ai_memory_events enable row level security;
alter table public.knowledge_assets enable row level security;
alter table public.marketplace_connections enable row level security;
alter table public.profit_snapshots enable row level security;
do $$ begin create policy "dev_ai_ceo_briefs_all" on public.ai_ceo_briefs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_ai_memory_events_all" on public.ai_memory_events for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_knowledge_assets_all" on public.knowledge_assets for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_marketplace_connections_all" on public.marketplace_connections for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_profit_snapshots_all" on public.profit_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;

insert into public.marketplace_connections(marketplace_code, marketplace_name, status, automation_level, health_message)
values
 ('coupang','쿠팡','connected',3,'Seller Engine 연결'),
 ('naver','스마트스토어','planned',0,'확장 대기'),
 ('11st','11번가','planned',0,'확장 대기'),
 ('gmarket','G마켓','planned',0,'확장 대기'),
 ('amazon','Amazon','planned',0,'글로벌 확장 대기'),
 ('shopee','Shopee','planned',0,'동남아 확장 대기')
on conflict (marketplace_code) do nothing;

insert into public.knowledge_assets(asset_type,title,summary,status,tags)
values
 ('policy','Revenue First 운영 원칙','매출과 공헌이익에 직접 연결되는 작업을 최우선으로 실행합니다.','active',array['revenue','governance']),
 ('playbook','상품 발굴→등록 표준 Playbook','상품 발굴부터 쿠팡 등록 준비까지의 12단계 표준 실행 흐름입니다.','active',array['workflow','coupang']),
 ('sop','AI Decision 승인 SOP','근거·신뢰도·리스크를 확인한 뒤 고위험 작업만 대표 승인으로 전환합니다.','active',array['decision','approval'])
on conflict do nothing;

insert into public.ai_ceo_briefs(brief_date,headline,executive_summary,priorities,recommended_actions,risks,confidence,status)
values(current_date,'매출 파이프라인을 가동할 준비가 되었습니다.','상품 후보와 실제 매출 데이터가 아직 부족하므로 첫 실상품의 발굴·검증·등록을 최우선으로 진행합니다.',
 '["첫 상품 후보 20개 발굴","상위 5개 수익성 분석","1개 상품 등록 준비"]'::jsonb,
 '["전체 자동 실행으로 발굴 시작","마진 기준 미달 상품 자동 제외","쿠팡 제출 전 대표 승인"]'::jsonb,
 '["실데이터 부족","공급가·배송비 미확정","쿠팡 API 운영키 검증 필요"]'::jsonb,82,'approved')
on conflict (brief_date) do nothing;

insert into public.system_releases(version, release_name, status, migration_name, release_notes, rollback_notes, released_at)
values ('11.0.0','Autonomous Company Enterprise','released','018_autonomous_company_enterprise.sql',
'AI CEO Brief, Product/Profit Center, AI Memory, Knowledge Center, Notification Center, Marketplace Center와 자율운영 준비도를 통합합니다.',
'애플리케이션을 v10.2 패키지로 복원합니다. 018의 신규 테이블은 데이터 보존을 위해 유지할 수 있습니다.', now())
on conflict (version) do update set status='released', migration_name=excluded.migration_name, release_notes=excluded.release_notes, released_at=coalesce(public.system_releases.released_at, now()), updated_at=now();
