-- Gonggamline AI · Blueprint v2.0 · Sprint 1 Revenue Core Foundation
-- Run after 018_autonomous_company_enterprise.sql. Additive and idempotent.

create table if not exists public.revenue_opportunities (
  id bigint generated by default as identity primary key,
  opportunity_code text not null unique,
  keyword text not null,
  title text not null,
  source text not null default 'manual',
  source_product_id text,
  status text not null default 'idea' check (status in ('idea','candidate','evaluating','approved','content','ready','published','selling','learning','rejected','archived')),
  demand_score numeric not null default 0 check (demand_score between 0 and 100),
  margin_score numeric not null default 0 check (margin_score between 0 and 100),
  competition_score numeric not null default 0 check (competition_score between 0 and 100),
  supply_score numeric not null default 0 check (supply_score between 0 and 100),
  risk_score numeric not null default 0 check (risk_score between 0 and 100),
  listing_score numeric not null default 0 check (listing_score between 0 and 100),
  revenue_score numeric not null default 0 check (revenue_score between 0 and 100),
  ai_confidence numeric not null default 0 check (ai_confidence between 0 and 100),
  estimated_sale_price numeric not null default 0,
  estimated_cost numeric not null default 0,
  estimated_profit numeric not null default 0,
  expected_monthly_sales integer not null default 0,
  evidence jsonb not null default '[]'::jsonb,
  reasons jsonb not null default '[]'::jsonb,
  risks jsonb not null default '[]'::jsonb,
  next_action text,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.runtime_jobs (
  id bigint generated by default as identity primary key,
  job_code text not null unique,
  opportunity_id bigint references public.revenue_opportunities(id) on delete set null,
  worker_code text not null,
  job_type text not null,
  status text not null default 'queued' check (status in ('queued','running','waiting','completed','failed','retry','archived')),
  priority integer not null default 50 check (priority between 0 and 100),
  attempts integer not null default 0,
  max_attempts integer not null default 3,
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  error_message text,
  scheduled_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.revenue_decisions (
  id bigint generated by default as identity primary key,
  opportunity_id bigint references public.revenue_opportunities(id) on delete cascade,
  decision_type text not null,
  decision text not null,
  reason text,
  evidence jsonb not null default '[]'::jsonb,
  confidence numeric not null default 0 check (confidence between 0 and 100),
  expected_impact numeric not null default 0,
  actual_impact numeric,
  result text,
  learning text,
  created_at timestamptz not null default now()
);

create index if not exists revenue_opportunities_score_idx on public.revenue_opportunities(revenue_score desc, created_at desc);
create index if not exists revenue_opportunities_status_idx on public.revenue_opportunities(status, updated_at desc);
create index if not exists runtime_jobs_queue_idx on public.runtime_jobs(status, priority desc, scheduled_at asc);
create index if not exists revenue_decisions_opportunity_idx on public.revenue_decisions(opportunity_id, created_at desc);

alter table public.revenue_opportunities enable row level security;
alter table public.runtime_jobs enable row level security;
alter table public.revenue_decisions enable row level security;
do $$ begin create policy "dev_revenue_opportunities_all" on public.revenue_opportunities for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_runtime_jobs_all" on public.runtime_jobs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "dev_revenue_decisions_all" on public.revenue_decisions for all using (true) with check (true); exception when duplicate_object then null; end $$;

insert into public.revenue_opportunities(opportunity_code,keyword,title,source,status,demand_score,margin_score,competition_score,supply_score,risk_score,listing_score,revenue_score,ai_confidence,estimated_sale_price,estimated_cost,estimated_profit,expected_monthly_sales,reasons,risks,next_action)
values
 ('OPP-DEMO-001','케이블정리','책상 밑 케이블 정리 트레이','demo','candidate',78,74,61,82,21,68,74,84,19900,8200,11700,120,'["반복 수요","비브랜드 진입 가능"]'::jsonb,'["가격 경쟁"]'::jsonb,'AI 평가 실행'),
 ('OPP-DEMO-002','욕실수납','무타공 욕실 코너 선반','demo','evaluating',82,79,58,76,29,73,76,80,15900,6100,9800,150,'["생활 필수 카테고리","콘텐츠 차별화 가능"]'::jsonb,'["후기 경쟁"]'::jsonb,'CEO 승인 검토')
on conflict (opportunity_code) do nothing;

insert into public.runtime_jobs(job_code,opportunity_id,worker_code,job_type,status,priority,input_payload)
select 'JOB-DEMO-001', id, 'ai-profit', 'evaluate_opportunity', 'queued', revenue_score, jsonb_build_object('opportunityId',id)
from public.revenue_opportunities where opportunity_code='OPP-DEMO-001'
on conflict (job_code) do nothing;

insert into public.system_releases(version, release_name, status, migration_name, release_notes, rollback_notes, released_at)
values ('11.0.0-sprint.1','Sprint 1 Revenue Core Foundation','released','019_sprint1_revenue_core_foundation.sql',
'Revenue Opportunity, Revenue Score, Runtime Job Queue, Decision Record, Revenue Center UI/API를 추가합니다.',
'애플리케이션 코드를 v11.0으로 복원합니다. 신규 테이블은 데이터 보존 목적으로 유지하거나 ROLLBACK-Sprint1.md 절차로 제거합니다.',now())
on conflict (version) do update set status='released', migration_name=excluded.migration_name, release_notes=excluded.release_notes, released_at=coalesce(public.system_releases.released_at,now()), updated_at=now();
