-- Gonggamline AI · Blueprint v2.0 · Sprint 2 Runtime Execution
-- Run after 019_sprint1_revenue_core_foundation.sql. Additive and idempotent.

alter table public.runtime_jobs
  add column if not exists locked_by text,
  add column if not exists locked_at timestamptz,
  add column if not exists last_heartbeat_at timestamptz,
  add column if not exists duration_ms integer,
  add column if not exists result_summary text;

create table if not exists public.worker_runtime_events (
  id bigint generated by default as identity primary key,
  runtime_job_id bigint references public.runtime_jobs(id) on delete cascade,
  opportunity_id bigint references public.revenue_opportunities(id) on delete set null,
  worker_code text not null,
  event_type text not null check (event_type in ('claimed','started','progress','completed','failed','retry','cancelled')),
  message text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists worker_runtime_events_job_idx on public.worker_runtime_events(runtime_job_id, created_at desc);
create index if not exists worker_runtime_events_worker_idx on public.worker_runtime_events(worker_code, created_at desc);

alter table public.worker_runtime_events enable row level security;
do $$ begin create policy "dev_worker_runtime_events_all" on public.worker_runtime_events for all using (true) with check (true); exception when duplicate_object then null; end $$;

insert into public.system_releases(version, release_name, status, migration_name, release_notes, rollback_notes, released_at)
values ('11.0.0-sprint.2','Sprint 2 Runtime Execution','released','020_sprint2_runtime_execution.sql',
'Queue Claim, Worker Executor, Retry/Cancel, Runtime Event Log, AI Memory 기록, Revenue Center 실행 제어를 추가합니다.',
'애플리케이션 코드를 Sprint 1로 복원합니다. 신규 컬럼과 worker_runtime_events 테이블은 데이터 보존을 위해 유지하거나 ROLLBACK-Sprint2.md 절차로 제거합니다.',now())
on conflict (version) do update set status='released', migration_name=excluded.migration_name, release_notes=excluded.release_notes, released_at=coalesce(public.system_releases.released_at,now()), updated_at=now();
