-- Autonomous Market Trend & Item Discovery Engine v1.
-- Additive evidence/read-model migration; no existing verdict or commerce state is changed.

alter table public.market_keywords add column if not exists discovery_lane text not null default 'CORE';
alter table public.market_keywords add column if not exists evidence_count integer not null default 0;
alter table public.market_keywords add column if not exists promoted_at timestamptz;
alter table public.market_keywords add column if not exists paused_reason text;

do $$ begin
  alter table public.market_keywords add constraint market_keywords_discovery_lane_check
    check (discovery_lane in ('CORE','EXPLORE','WATCH','QUARANTINED'));
exception when duplicate_object then null; end $$;

create table if not exists public.market_keyword_signal_snapshots (
  id bigint generated by default as identity primary key,
  market_keyword_id bigint references public.market_keywords(id) on delete cascade,
  concept text not null,
  provider text not null,
  metric_type text not null default 'relative_demand',
  demand_index numeric(7,2),
  content_velocity numeric(10,2),
  shopping_intent numeric(7,2),
  competition_pressure numeric(7,2),
  price_room numeric(7,2),
  source_rank integer,
  request_count integer not null default 0,
  quota_units integer not null default 0,
  reported_cost_usd numeric(12,6) not null default 0,
  evidence_digest text not null unique,
  evidence jsonb not null default '{}'::jsonb,
  observed_at timestamptz not null,
  received_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.market_concepts (
  id bigint generated by default as identity primary key,
  canonical_phrase text not null unique,
  aliases jsonb not null default '[]'::jsonb,
  category text,
  category_code text,
  lifecycle text not null default 'WATCH' check (lifecycle in ('WATCH','EXPLORE','ACTIVE','PAUSED','QUARANTINED')),
  evidence_count integer not null default 0,
  source_count integer not null default 0,
  conflict_state text not null default 'CLEAR' check (conflict_state in ('CLEAR','UNKNOWN','CONFLICT','PROHIBITED')),
  last_evidence_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_candidate_entities (
  id bigint generated by default as identity primary key,
  entity_key text not null unique,
  canonical_title text not null,
  candidate_form text not null default 'single' check (candidate_form in ('single','set','bundle','multipack')),
  market_product_ids jsonb not null default '[]'::jsonb,
  concept_ids jsonb not null default '[]'::jsonb,
  identity_confidence integer not null default 0 check (identity_confidence between 0 and 100),
  evidence_digest text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.market_trend_digests (
  id bigint generated by default as identity primary key,
  version text not null,
  digest text not null unique,
  status text not null check (status in ('COMPLETE','PARTIAL','EMPTY')),
  as_of timestamptz not null,
  provider_health jsonb not null default '{}'::jsonb,
  output jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists public.market_recommendation_runs (
  id bigint generated by default as identity primary key,
  trend_digest_id bigint references public.market_trend_digests(id) on delete restrict,
  version text not null,
  digest text not null unique,
  status text not null check (status in ('COMPLETE','PARTIAL','EMPTY','FAILED')),
  recommendation_count integer not null default 0,
  output jsonb not null default '{}'::jsonb,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.market_provider_usage (
  id bigint generated by default as identity primary key,
  provider text not null,
  usage_day date not null,
  request_count integer not null default 0,
  quota_units integer not null default 0,
  reported_cost_usd numeric(12,6) not null default 0,
  request_ceiling_usd numeric(12,6),
  daily_ceiling_usd numeric(12,6),
  trip_state text not null default 'OPEN' check (trip_state in ('OPEN','TRIPPED','DISABLED')),
  last_error text,
  updated_at timestamptz not null default now(),
  unique(provider, usage_day)
);

create index if not exists market_keyword_signal_concept_time_idx on public.market_keyword_signal_snapshots(concept, observed_at desc);
create index if not exists market_keyword_signal_keyword_time_idx on public.market_keyword_signal_snapshots(market_keyword_id, observed_at desc);
create index if not exists market_trend_digests_as_of_idx on public.market_trend_digests(as_of desc);
create index if not exists market_recommendation_runs_completed_idx on public.market_recommendation_runs(completed_at desc);

alter table public.market_keyword_signal_snapshots enable row level security;
alter table public.market_concepts enable row level security;
alter table public.market_candidate_entities enable row level security;
alter table public.market_trend_digests enable row level security;
alter table public.market_recommendation_runs enable row level security;
alter table public.market_provider_usage enable row level security;

do $$ begin create policy "market_keyword_signal_snapshots_all" on public.market_keyword_signal_snapshots for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "market_concepts_all" on public.market_concepts for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "market_candidate_entities_all" on public.market_candidate_entities for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "market_trend_digests_all" on public.market_trend_digests for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "market_recommendation_runs_all" on public.market_recommendation_runs for all using (true) with check (true); exception when duplicate_object then null; end $$;
do $$ begin create policy "market_provider_usage_all" on public.market_provider_usage for all using (true) with check (true); exception when duplicate_object then null; end $$;
