-- 15A-EXT: append-only external evidence and import audit.
-- Additive migration; existing market and commerce state is preserved.

create table if not exists public.external_market_signal_packets (
  id bigint generated by default as identity primary key,
  packet_version text not null,
  source text not null check (source in ('TENBI','NAVER','TIKTOK','COUPANG')),
  upstream_source text not null, observed_via text not null,
  keyword_id text not null, platform_product_id text, source_url text,
  category_binding text, collected_at timestamptz not null, valid_until timestamptz not null,
  packet jsonb not null, provenance_digest text not null, output_digest text not null unique,
  created_at timestamptz not null default now()
);
create index if not exists external_market_signal_packets_keyword_time_idx on public.external_market_signal_packets(keyword_id, collected_at desc);
create table if not exists public.external_market_import_history (
  id bigint generated by default as identity primary key, source text not null,
  source_digest text not null unique, imported_at timestamptz not null default now(),
  accepted_count integer not null default 0, rejected_count integer not null default 0,
  rejected_rows jsonb not null default '[]'::jsonb
);
alter table public.external_market_signal_packets enable row level security;
alter table public.external_market_import_history enable row level security;
