"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Event={id:number;stage:string;title:string;created_at:string};
type Workflow={id:number;workflow_name:string;current_stage:string;status:string;updated_at:string;commerce_timeline_events:Event[];order:null|{id:number;order_number:string;status:string;quantity:number;total_amount:number;expected_inbound_date:string|null;suppliers:{name:string}|null};inbound:null|{warehouse_name:string;status:string;expected_quantity:number;received_quantity:number;expected_inbound_date:string|null};draft:null|{id:number;status:string;coupang_title:string;revision:number};mapping:null|{provider:string;provider_product_id:string;provider_product_name:string;current_unit_cost:number;stock_status:string;suppliers:{name:string}|null};quote:null|{product_name:string;moq:number;unit_cost:number;status:string;sourcing_decisions:Array<{decision:string;expected_margin_rate:number;score:number}>}};
const stages=["market_discovered","ai_recommended","human_approved","supplier_mapped","quote_selected","purchase_approved","purchase_ordered","three_pl_inbound","listing_ready","coupang_registered","selling","learning"];
const labels:Record<string,string>={market_discovered:"시장 발견",ai_recommended:"AI 추천",human_approved:"승인",supplier_mapped:"도매 연결",quote_selected:"견적 선정",purchase_approved:"발주 승인",purchase_ordered:"발주 완료",three_pl_inbound:"3PL 입고",listing_ready:"Listing",coupang_registered:"쿠팡 등록",selling:"판매",learning:"학습"};
const won=(n:number)=>`${Math.round(Number(n)||0).toLocaleString("ko-KR")}원`;
export default function WorkspacePage(){const[rows,setRows]=useState<Workflow[]>([]),[selectedId,setSelectedId]=useState<number|null>(null),[error,setError]=useState("");async function load(){const r=await fetch("/api/workspace",{cache:"no-store"});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||"Workspace 조회 실패");setRows(d.workflows||[]);setSelectedId(v=>v??d.workflows?.[0]?.id??null);}useEffect(()=>{load().catch(e=>setError(e.message));},[]);const selected=useMemo(()=>rows.find(x=>x.id===selectedId)||rows[0],[rows,selectedId]);const currentIndex=selected?stages.indexOf(selected.current_stage):-1;return <main className="dashboard">
<section className="hero" style={{background:"linear-gradient(135deg,#122c59,#1b76a8)"}}><div><p className="eyebrow">ENGINE 4-1 · FULFILLMENT WORKSPACE</p><h1>4-1. 물류·재고 통합 Workspace</h1><p className="hero-description">시장 발견부터 AI 추천, 국내 도매 소싱, 발주, 3PL, Listing, 쿠팡 등록, 판매와 학습까지 상품 하나의 전체 상태와 이력을 한 화면에서 확인합니다.</p></div></section>
<section className="stat-grid"><article><span>전체 Workflow</span><strong>{rows.length}</strong></article><article><span>조달 진행</span><strong>{rows.filter(x=>["purchase_approved","purchase_ordered","three_pl_inbound"].includes(x.current_stage)).length}</strong></article><article><span>Listing 준비</span><strong>{rows.filter(x=>x.current_stage==="listing_ready").length}</strong></article><article><span>쿠팡 등록</span><strong>{rows.filter(x=>x.current_stage==="coupang_registered").length}</strong></article></section>{error&&<div className="notice error-notice">{error}</div>}
<section style={{display:"grid",gridTemplateColumns:"minmax(260px,0.8fr) minmax(0,2.2fr)",gap:16,alignItems:"start"}}><aside className="panel"><div className="section-heading"><div><h2>상품 Workflow</h2><p>상품을 선택하세요.</p></div><button className="secondary-button" onClick={()=>load().catch(e=>setError(e.message))}>새로고침</button></div><div style={{display:"grid",gap:8}}>{rows.length?rows.map(w=><button key={w.id} onClick={()=>setSelectedId(w.id)} style={{textAlign:"left",padding:12,borderRadius:10,border:w.id===selected?.id?"2px solid #2563eb":"1px solid #d9e1ec",background:"white",color:"#111827"}}><strong>{w.workflow_name}</strong><small style={{display:"block",marginTop:4}}>{labels[w.current_stage]||w.current_stage} · {w.status}</small></button>):<p className="empty-copy">조달 Workflow가 없습니다.</p>}</div></aside>
{selected?<section style={{display:"grid",gap:16}}><article className="panel"><div className="section-heading"><div><p className="eyebrow" style={{color:"#2563eb"}}>WORKFLOW #{selected.id}</p><h2>{selected.workflow_name}</h2><p>{labels[selected.current_stage]||selected.current_stage} · 최근 변경 {new Date(selected.updated_at).toLocaleString("ko-KR")}</p></div><div className="hero-actions" style={{flexDirection:"row",flexWrap:"wrap"}}><Link className="button-link" href="/listing">Listing 생성</Link><Link className="button-link secondary-button" href="/coupang/register">쿠팡 등록</Link></div></div><div style={{display:"flex",gap:6,flexWrap:"wrap",marginTop:14}}>{stages.map((s,i)=><span key={s} style={{padding:"8px 10px",borderRadius:9,fontSize:12,fontWeight:700,background:i<=currentIndex?"#dbeafe":"#f1f5f9",color:i<=currentIndex?"#1d4ed8":"#64748b"}}>{i<currentIndex?"✓ ":i===currentIndex?"● ":""}{labels[s]}</span>)}</div></article>
<section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(230px,1fr))",gap:12}}><article className="panel"><h3>국내 공급처</h3>{selected.mapping?<><p><strong>{selected.mapping.suppliers?.name||"공급처"}</strong></p><p>{selected.mapping.provider} #{selected.mapping.provider_product_id}</p><p>{selected.mapping.provider_product_name}</p><p>공급가 {won(selected.mapping.current_unit_cost)} · {selected.mapping.stock_status}</p></>:<p className="empty-copy">연결 정보 없음</p>}</article><article className="panel"><h3>견적·수익성</h3>{selected.quote?<><p>{selected.quote.product_name}</p><p>MOQ {selected.quote.moq} · 견적 {won(selected.quote.unit_cost)}</p><p>{selected.quote.sourcing_decisions?.[0]?`판단 ${selected.quote.sourcing_decisions[0].decision} · 마진 ${Number(selected.quote.sourcing_decisions[0].expected_margin_rate).toFixed(1)}% · 점수 ${Math.round(selected.quote.sourcing_decisions[0].score)}`:"판단 대기"}</p></>:<p className="empty-copy">견적 정보 없음</p>}</article><article className="panel"><h3>발주</h3>{selected.order?<><p><strong>{selected.order.order_number}</strong></p><p>{selected.order.status} · {selected.order.quantity}개</p><p>{won(selected.order.total_amount)}</p><p>입고 예정 {selected.order.expected_inbound_date||"미정"}</p></>:<p className="empty-copy">발주 정보 없음</p>}</article><article className="panel"><h3>3PL</h3>{selected.inbound?<><p>{selected.inbound.warehouse_name}</p><p>{selected.inbound.status}</p><p>예정 {selected.inbound.expected_quantity} · 입고 {selected.inbound.received_quantity}</p><p>{selected.inbound.expected_inbound_date||"일정 미정"}</p></>:<p className="empty-copy">입고 계획 없음</p>}</article><article className="panel"><h3>Listing</h3>{selected.draft?<><p><strong>{selected.draft.coupang_title}</strong></p><p>{selected.draft.status} · revision {selected.draft.revision}</p><Link className="button-link" href="/listing">초안 검토</Link></>:<><p className="empty-copy">Listing 초안 없음</p><Link className="button-link" href="/listing">초안 생성</Link></>}</article></section>
<article className="panel"><h2>Commerce Timeline</h2><div style={{display:"grid",gap:10,marginTop:12}}>{[...(selected.commerce_timeline_events||[])].sort((a,b)=>b.id-a.id).map(e=><div key={e.id} style={{borderLeft:"4px solid #2563eb",padding:"8px 12px",background:"#f8fafc",borderRadius:8}}><strong>{e.title}</strong><small style={{display:"block",marginTop:4}}>{labels[e.stage]||e.stage} · {new Date(e.created_at).toLocaleString("ko-KR")}</small></div>)}</div></article></section>:<section className="panel"><p className="empty-copy">상품 Workflow를 생성하세요.</p></section>}</section>
</main>}
